622d3c3baea25d15fad9cde25e20aeece5384588
diff --git a/firmware_common/bladeRF.h b/firmware_common/bladeRF.h
index 7aeffa6d70d69d6a728cfcbe7a26332abdfc520d..85a2678bd81fb972ae22a9cf43a7c38b02026e6c 100644
--- a/firmware_common/bladeRF.h
+++ b/firmware_common/bladeRF.h
@@ -127,10 +127,12 @@ struct bladeRF_sector {
 #define NUM_DATA_URB    (1024)
 #define DATA_BUF_SZ     (1024*4)
 
-#define UART_PKT_DEV_GPIO_ADDR  0
-#define UART_PKT_DEV_DC_CORR_ADDR   4
-#define UART_PKT_DEV_GAIN_PHASE_CORR_ADDR 8
-#define UART_PKT_DEV_FGPA_VERSION_ID 12
+#define UART_PKT_DEV_GPIO_ADDR          0
+#define UART_PKT_DEV_RX_PHASE_ADDR      4
+#define UART_PKT_DEV_RX_GAIN_ADDR       6
+#define UART_PKT_DEV_TX_PHASE_ADDR      8
+#define UART_PKT_DEV_TX_GAIN_ADDR       10
+#define UART_PKT_DEV_FGPA_VERSION_ID    12
 
 struct uart_pkt {
     unsigned char magic;
diff --git a/hdl/fpga/ip/altera/nios_system/nios_system.qsys b/hdl/fpga/ip/altera/nios_system/nios_system.qsys
index 53de41619415a94cb6767d42e0a3d083e2433cf3..6ffb3bce0f7ea24d2afc0bd893ae15fe6dc4715c 100644
--- a/hdl/fpga/ip/altera/nios_system/nios_system.qsys
+++ b/hdl/fpga/ip/altera/nios_system/nios_system.qsys
@@ -44,7 +44,7 @@
          type = "int";
       }
    }
-   element correction_dc
+   element iq_corr_rx_phase_gain
    {
       datum _sortIndex
       {
@@ -52,7 +52,7 @@
          type = "int";
       }
    }
-   element correction_phase_gain
+   element iq_corr_tx_phase_gain
    {
       datum _sortIndex
       {
@@ -100,23 +100,23 @@
          type = "int";
       }
    }
-   element timer_0.s1
+   element uart_0.s1
    {
       datum baseAddress
       {
-         value = "36864";
+         value = "36992";
          type = "String";
       }
    }
-   element uart_0.s1
+   element timer_0.s1
    {
       datum baseAddress
       {
-         value = "36992";
+         value = "36864";
          type = "String";
       }
    }
-   element correction_phase_gain.s1
+   element iq_corr_tx_phase_gain.s1
    {
       datum baseAddress
       {
@@ -124,19 +124,19 @@
          type = "String";
       }
    }
-   element onchip_memory2_0.s1
+   element pio_0.s1
    {
       datum baseAddress
       {
-         value = "16384";
+         value = "36928";
          type = "String";
       }
    }
-   element pio_0.s1
+   element onchip_memory2_0.s1
    {
       datum baseAddress
       {
-         value = "36928";
+         value = "16384";
          type = "String";
       }
    }
@@ -202,8 +202,8 @@
  <parameter name="maxAdditionalLatency" value="1" />
  <parameter name="projectName" value="" />
  <parameter name="sopcBorderPoints" value="false" />
- <parameter name="systemHash" value="0" />
- <parameter name="timeStamp" value="0" />
+ <parameter name="systemHash" value="1" />
+ <parameter name="timeStamp" value="1386729013695" />
  <parameter name="useTestBenchNamingPattern" value="false" />
  <instanceScript></instanceScript>
  <interface name="clk" internal="clk_0.clk_in" type="clock" dir="end" />
@@ -221,13 +221,13 @@
    type="conduit"
    dir="end" />
  <interface
-   name="correction_dc"
-   internal="correction_dc.external_connection"
+   name="correction_rx_phase_gain"
+   internal="iq_corr_rx_phase_gain.external_connection"
    type="conduit"
    dir="end" />
  <interface
-   name="correction_phase_gain"
-   internal="correction_phase_gain.external_connection"
+   name="correction_tx_phase_gain"
+   internal="iq_corr_tx_phase_gain.external_connection"
    type="conduit"
    dir="end" />
  <interface
@@ -235,7 +235,7 @@
    internal="bladerf_oc_i2c_master_0.conduit_end"
    type="conduit"
    dir="end" />
- <module kind="clock_source" version="13.1" enabled="1" name="clk_0">
+ <module kind="clock_source" version="13.0" enabled="1" name="clk_0">
   <parameter name="clockFrequency" value="80000000" />
   <parameter name="clockFrequencyKnown" value="true" />
   <parameter name="inputClockFrequency" value="0" />
@@ -243,7 +243,7 @@
  </module>
  <module
    kind="altera_nios2_qsys"
-   version="13.1"
+   version="13.0"
    enabled="1"
    name="nios2_qsys_0">
   <parameter name="setting_showUnpublishedSettings" value="false" />
@@ -270,14 +270,11 @@
   <parameter name="setting_alwaysEncrypt" value="true" />
   <parameter name="setting_allowFullAddressRange" value="false" />
   <parameter name="setting_activateTrace" value="true" />
-  <parameter name="setting_activateTrace_user" value="false" />
   <parameter name="setting_activateTestEndChecker" value="false" />
-  <parameter name="setting_ecc_sim_test_ports" value="false" />
   <parameter name="setting_activateMonitors" value="true" />
   <parameter name="setting_activateModelChecker" value="false" />
   <parameter name="setting_HDLSimCachesCleared" value="true" />
   <parameter name="setting_HBreakTest" value="false" />
-  <parameter name="setting_breakslaveoveride" value="false" />
   <parameter name="muldiv_divider" value="false" />
   <parameter name="mpu_useLimit" value="false" />
   <parameter name="mpu_enabled" value="false" />
@@ -335,12 +332,6 @@
   <parameter name="dcache_lineSize" value="32" />
   <parameter name="setting_exportvectors" value="false" />
   <parameter name="setting_ecc_present" value="false" />
-  <parameter name="setting_ic_ecc_present" value="true" />
-  <parameter name="setting_rf_ecc_present" value="true" />
-  <parameter name="setting_mmu_ecc_present" value="true" />
-  <parameter name="setting_dc_ecc_present" value="false" />
-  <parameter name="setting_itcm_ecc_present" value="false" />
-  <parameter name="setting_dtcm_ecc_present" value="false" />
   <parameter name="regfile_ramBlockType" value="Automatic" />
   <parameter name="ocimem_ramBlockType" value="Automatic" />
   <parameter name="mmu_ramBlockType" value="Automatic" />
@@ -356,12 +347,12 @@
   <parameter name="tightlyCoupledInstructionMaster2AddrWidth" value="1" />
   <parameter name="tightlyCoupledInstructionMaster3AddrWidth" value="1" />
   <parameter name="instSlaveMapParam"><![CDATA[<address-map><slave name='onchip_memory2_0.s1' start='0x4000' end='0x8000' /><slave name='nios2_qsys_0.jtag_debug_module' start='0x8800' end='0x9000' /></address-map>]]></parameter>
-  <parameter name="dataSlaveMapParam"><![CDATA[<address-map><slave name='correction_dc.s1' start='0x0' end='0x10' /><slave name='onchip_memory2_0.s1' start='0x4000' end='0x8000' /><slave name='nios2_qsys_0.jtag_debug_module' start='0x8800' end='0x9000' /><slave name='timer_0.s1' start='0x9000' end='0x9040' /><slave name='pio_0.s1' start='0x9040' end='0x9060' /><slave name='spi_1.spi_control_port' start='0x9060' end='0x9080' /><slave name='uart_0.s1' start='0x9080' end='0x90A0' /><slave name='spi_0.spi_control_port' start='0x90A0' end='0x90C0' /><slave name='jtag_uart_0.avalon_jtag_slave' start='0x90C8' end='0x90D0' /><slave name='bladerf_oc_i2c_master_0.bladerf_oc_i2c_master' start='0x90E0' end='0x90E8' /><slave name='correction_phase_gain.s1' start='0x9100' end='0x9110' /></address-map>]]></parameter>
+  <parameter name="dataSlaveMapParam"><![CDATA[<address-map><slave name='iq_corr_rx_phase_gain.s1' start='0x0' end='0x10' /><slave name='onchip_memory2_0.s1' start='0x4000' end='0x8000' /><slave name='nios2_qsys_0.jtag_debug_module' start='0x8800' end='0x9000' /><slave name='timer_0.s1' start='0x9000' end='0x9040' /><slave name='pio_0.s1' start='0x9040' end='0x9060' /><slave name='spi_1.spi_control_port' start='0x9060' end='0x9080' /><slave name='uart_0.s1' start='0x9080' end='0x90A0' /><slave name='spi_0.spi_control_port' start='0x90A0' end='0x90C0' /><slave name='jtag_uart_0.avalon_jtag_slave' start='0x90C8' end='0x90D0' /><slave name='bladerf_oc_i2c_master_0.bladerf_oc_i2c_master' start='0x90E0' end='0x90E8' /><slave name='iq_corr_tx_phase_gain.s1' start='0x9100' end='0x9110' /></address-map>]]></parameter>
   <parameter name="clockFrequency" value="80000000" />
   <parameter name="deviceFamilyName" value="Cyclone IV E" />
   <parameter name="internalIrqMaskSystemInfo" value="63" />
   <parameter name="customInstSlavesSystemInfo" value="&lt;info/&gt;" />
-  <parameter name="deviceFeaturesSystemInfo">ADDRESS_STALL 1 ADVANCED_INFO 0 ANY_QFP 0 CELL_LEVEL_BACK_ANNOTATION_DISABLED 0 COMPILER_SUPPORT 1 DSP 0 DSP_SHIFTER_BLOCK 0 DUMP_ASM_LAB_BITS_FOR_POWER 1 EMUL 1 ENABLE_ADVANCED_IO_ANALYSIS_GUI_FEATURES 1 ENABLE_PIN_PLANNER 0 ENGINEERING_SAMPLE 0 EPCS 1 ESB 0 FAKE1 0 FAKE2 0 FAKE3 0 FAMILY_LEVEL_INSTALLATION_ONLY 1 FASTEST 0 FINAL_TIMING_MODEL 0 FITTER_USE_FALLING_EDGE_DELAY 0 GENERATE_DC_ON_CURRENT_WARNING_FOR_INTERNAL_CLAMPING_DIODE 0 HARDCOPY 0 HAS_18_BIT_MULTS 0 HAS_ACE_SUPPORT 1 HAS_ACTIVE_PARALLEL_FLASH_SUPPORT 0 HAS_ADJUSTABLE_OUTPUT_IO_TIMING_MEAS_POINT 0 HAS_ADVANCED_IO_INVERTED_CORNER 0 HAS_ADVANCED_IO_POWER_SUPPORT 1 HAS_ADVANCED_IO_TIMING_SUPPORT 1 HAS_ALM_SUPPORT 0 HAS_ATOM_AND_ROUTING_POWER_MODELED_TOGETHER 0 HAS_AUTO_DERIVE_CLOCK_UNCERTAINTY_SUPPORT 0 HAS_AUTO_FIT_SUPPORT 1 HAS_BALANCED_OPT_TECHNIQUE_SUPPORT 1 HAS_BENEFICIAL_SKEW_SUPPORT 1 HAS_BITLEVEL_DRIVE_STRENGTH_CONTROL 1 HAS_BSDL_FILE_GENERATION 1 HAS_CDB_RE_NETWORK_PRESERVATION_SUPPORT 0 HAS_CGA_SUPPORT 1 HAS_CHECK_NETLIST_SUPPORT 0 HAS_CLOCK_REGION_CHECKER_ENABLED 1 HAS_CORE_JUNCTION_TEMP_DERATING 0 HAS_CROSSTALK_SUPPORT 0 HAS_CUSTOM_REGION_SUPPORT 1 HAS_DAP_JTAG_FROM_HPS 0 HAS_DATA_DRIVEN_ACVQ_HSSI_SUPPORT 0 HAS_DDB_FDI_SUPPORT 0 HAS_DESIGN_ANALYZER_SUPPORT 1 HAS_DETAILED_IO_RAIL_POWER_MODEL 1 HAS_DETAILED_LEIM_STATIC_POWER_MODEL 1 HAS_DETAILED_LE_POWER_MODEL 1 HAS_DETAILED_ROUTING_MUX_STATIC_POWER_MODEL 1 HAS_DETAILED_THERMAL_CIRCUIT_PARAMETER_SUPPORT 1 HAS_DEVICE_MIGRATION_SUPPORT 1 HAS_DIAGONAL_MIGRATION_SUPPORT 0 HAS_EMIF_TOOLKIT_SUPPORT 0 HAS_ERROR_DETECTION_SUPPORT 0 HAS_FAMILY_VARIANT_MIGRATION_SUPPORT 0 HAS_FANOUT_FREE_NODE_SUPPORT 1 HAS_FAST_FIT_SUPPORT 1 HAS_FITTER_EARLY_TIMING_ESTIMATE_SUPPORT 1 HAS_FITTER_ECO_SUPPORT 1 HAS_FIT_NETLIST_OPT_RETIME_SUPPORT 1 HAS_FIT_NETLIST_OPT_SUPPORT 1 HAS_FORMAL_VERIFICATION_SUPPORT 1 HAS_FPGA_XCHANGE_SUPPORT 1 HAS_FSAC_LUTRAM_REGISTER_PACKING_SUPPORT 0 HAS_FULL_DAT_MIN_TIMING_SUPPORT 1 HAS_FULL_INCREMENTAL_DESIGN_SUPPORT 1 HAS_FUNCTIONAL_SIMULATION_SUPPORT 1 HAS_FUNCTIONAL_VERILOG_SIMULATION_SUPPORT 0 HAS_FUNCTIONAL_VHDL_SIMULATION_SUPPORT 0 HAS_GLITCH_FILTERING_SUPPORT 1 HAS_HARDCOPYII_SUPPORT 0 HAS_HC_READY_SUPPORT 0 HAS_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_HOLD_TIME_AVOIDANCE_ACROSS_CLOCK_SPINE_SUPPORT 1 HAS_HSPICE_WRITER_SUPPORT 1 HAS_HSSI_POWER_CALCULATOR 0 HAS_IBISO_WRITER_SUPPORT 0 HAS_ICD_DATA_IP 0 HAS_INCREMENTAL_DAT_SUPPORT 1 HAS_INCREMENTAL_SYNTHESIS_SUPPORT 1 HAS_INTERFACE_PLANNER_SUPPORT 0 HAS_IO_ASSIGNMENT_ANALYSIS_SUPPORT 1 HAS_IO_DECODER 0 HAS_IO_PLACEMENT_OPTIMIZATION_SUPPORT 1 HAS_IO_SMART_RECOMPILE_SUPPORT 0 HAS_JITTER_SUPPORT 1 HAS_JTAG_SLD_HUB_SUPPORT 1 HAS_LIMITED_TCL_FITTER_SUPPORT 0 HAS_LOGICAL_FLOORPLANNER_SUPPORT 0 HAS_LOGIC_LOCK_SUPPORT 1 HAS_MICROPROCESSOR 0 HAS_MIF_SMART_COMPILE_SUPPORT 1 HAS_MINMAX_TIMING_MODELING_SUPPORT 1 HAS_MIN_TIMING_ANALYSIS_SUPPORT 1 HAS_MUX_RESTRUCTURE_SUPPORT 1 HAS_NEW_HC_FLOW_SUPPORT 0 HAS_NEW_SERDES_MAX_RESOURCE_COUNT_REPORTING_SUPPORT 1 HAS_NEW_VPR_SUPPORT 1 HAS_NONSOCKET_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_NO_HARDBLOCK_PARTITION_SUPPORT 0 HAS_NO_JTAG_USERCODE_SUPPORT 0 HAS_OPERATING_SETTINGS_AND_CONDITIONS_REPORTING_SUPPORT 1 HAS_PAD_LOCATION_ASSIGNMENT_SUPPORT 0 HAS_PARTIAL_RECONFIG_SUPPORT 0 HAS_PASSIVE_PARALLEL_SUPPORT 0 HAS_PHYSICAL_NETLIST_OUTPUT 0 HAS_PHYSICAL_ROUTING_SUPPORT 0 HAS_PIN_SPECIFIC_VOLTAGE_SUPPORT 1 HAS_PLDM_REF_SUPPORT 1 HAS_POWER_BINNING_LIMITS_DATA 0 HAS_POWER_ESTIMATION_SUPPORT 1 HAS_PRELIMINARY_CLOCK_UNCERTAINTY_NUMBERS 0 HAS_PRE_FITTER_FPP_SUPPORT 0 HAS_PRE_FITTER_LUTRAM_NETLIST_CHECKER_ENABLED 0 HAS_PVA_SUPPORT 1 HAS_RAPID_RECOMPILE_SUPPORT 0 HAS_RCF_SUPPORT 1 HAS_RCF_SUPPORT_FOR_DEBUGGING 0 HAS_RED_BLACK_SEPARATION_SUPPORT 0 HAS_RE_LEVEL_TIMING_GRAPH_SUPPORT 1 HAS_RISEFALL_DELAY_SUPPORT 1 HAS_SIGNAL_PROBE_SUPPORT 1 HAS_SIGNAL_TAP_SUPPORT 1 HAS_SIMULATOR_SUPPORT 0 HAS_SPLIT_IO_SUPPORT 1 HAS_SPLIT_LC_SUPPORT 1 HAS_STRICT_PRESERVATION_SUPPORT 1 HAS_SYNTH_FSYN_NETLIST_OPT_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_RETIME_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_SUPPORT 1 HAS_TCL_FITTER_SUPPORT 0 HAS_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_TEMPLATED_REGISTER_PACKING_SUPPORT 1 HAS_TIME_BORROWING_SUPPORT 0 HAS_TIMING_DRIVEN_SYNTHESIS_SUPPORT 1 HAS_TIMING_INFO_SUPPORT 1 HAS_TIMING_OPERATING_CONDITIONS 1 HAS_TIMING_SIMULATION_SUPPORT 1 HAS_TITAN_BASED_MAC_REGISTER_PACKER_SUPPORT 0 HAS_U2B2_SUPPORT 0 HAS_USER_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_USE_FITTER_INFO_SUPPORT 1 HAS_VCCPD_POWER_RAIL 0 HAS_VERTICAL_MIGRATION_SUPPORT 1 HAS_VIEWDRAW_SYMBOL_SUPPORT 0 HAS_VIO_SUPPORT 1 HAS_VIRTUAL_DEVICES 0 HAS_WYSIWYG_DFFEAS_SUPPORT 1 HAS_XIBISO_WRITER_SUPPORT 1 IFP_USE_LEGACY_IO_CHECKER 0 INCREMENTAL_DESIGN_SUPPORTS_COMPATIBLE_CONSTRAINTS 1 INSTALLED 0 INTERNAL_POF_SUPPORT_ENABLED 0 INTERNAL_USE_ONLY 0 ISSUE_MILITARY_TEMPERATURE_WARNING 0 IS_CONFIG_ROM 0 IS_DEFAULT_FAMILY 0 IS_HARDCOPY_FAMILY 0 IS_HBGA_PACKAGE 0 IS_HIGH_CURRENT_PART 0 IS_LOW_POWER_PART 0 IS_SDM_ONLY_PACKAGE 0 LVDS_IO 1 M10K_MEMORY 0 M144K_MEMORY 0 M20K_MEMORY 0 M4K_MEMORY 0 M512_MEMORY 0 M9K_MEMORY 1 MLAB_MEMORY 0 MRAM_MEMORY 0 NOT_LISTED 0 NOT_MIGRATABLE 0 NO_FITTER_DELAY_CACHE_GENERATED 0 NO_PIN_OUT 0 NO_POF 0 NO_RPE_SUPPORT 0 NO_SUPPORT_FOR_LOGICLOCK_CONTENT_BACK_ANNOTATION 1 NO_SUPPORT_FOR_STA_CLOCK_UNCERTAINTY_CHECK 0 NO_TDC_SUPPORT 0 POSTFIT_BAK_DATABASE_EXPORT_ENABLED 1 POSTMAP_BAK_DATABASE_EXPORT_ENABLED 1 PROGRAMMER_SUPPORT 1 QFIT_IN_DEVELOPMENT 0 QMAP_IN_DEVELOPMENT 0 RAM_LOGICAL_NAME_CHECKING_IN_CUT_ENABLED 1 REPORTS_METASTABILITY_MTBF 1 REQUIRES_INSTALLATION_PATCH 0 REQUIRES_LIST_OF_TEMPERATURE_AND_VOLTAGE_OPERATING_CONDITIONS 1 RESERVES_SIGNAL_PROBE_PINS 0 RESOLVE_MAX_FANOUT_EARLY 1 RESOLVE_MAX_FANOUT_LATE 0 RESPECTS_FIXED_SIZED_LOCKED_LOCATION_LOGICLOCK 1 RESTRICTED_USER_SELECTION 0 RISEFALL_SUPPORT_IS_HIDDEN 0 SHOW_HIDDEN_FAMILY_IN_PROGRAMMER 0 STRICT_TIMING_DB_CHECKS 0 SUPPORTS_ADDITIONAL_OPTIONS_FOR_UNUSED_IO 0 SUPPORTS_CRC 1 SUPPORTS_DIFFERENTIAL_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_DSP_BALANCING_BACK_ANNOTATION 0 SUPPORTS_GENERATION_OF_EARLY_POWER_ESTIMATOR_FILE 1 SUPPORTS_GLOBAL_SIGNAL_BACK_ANNOTATION 0 SUPPORTS_MAC_CHAIN_OUT_ADDER 0 SUPPORTS_RAM_PACKING_BACK_ANNOTATION 0 SUPPORTS_REG_PACKING_BACK_ANNOTATION 0 SUPPORTS_SIGNALPROBE_REGISTER_PIPELINING 1 SUPPORTS_SINGLE_ENDED_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_USER_MANUAL_LOGIC_DUPLICATION 1 TMV_RUN_CUSTOMIZABLE_VIEWER 1 TMV_RUN_INTERNAL_DETAILS 1 TMV_RUN_INTERNAL_DETAILS_ON_IO 0 TMV_RUN_INTERNAL_DETAILS_ON_IOBUF 1 TMV_RUN_INTERNAL_DETAILS_ON_LCELL 0 TMV_RUN_INTERNAL_DETAILS_ON_LRAM 0 TRANSCEIVER_3G_BLOCK 0 TRANSCEIVER_6G_BLOCK 0 USES_ACV_FOR_FLED 1 USES_ADB_FOR_BACK_ANNOTATION 1 USES_ALTERA_LNSIM 0 USES_ASIC_ROUTING_POWER_CALCULATOR 0 USES_DATA_DRIVEN_PLL_COMPUTATION_UTIL 1 USES_DEV 1 USES_ICP_FOR_ECO_FITTER 0 USES_LIBERTY_TIMING 0 USES_POWER_SIGNAL_ACTIVITIES 1 USES_THIRD_GENERATION_TIMING_MODELS_TIS 1 USES_U2B2_TIMING_MODELS 0 USE_ADVANCED_IO_POWER_BY_DEFAULT 1 USE_ADVANCED_IO_TIMING_BY_DEFAULT 1 USE_BASE_FAMILY_DDB_PATH 0 USE_OCT_AUTO_CALIBRATION 1 USE_RELAX_IO_ASSIGNMENT_RULES 0 USE_RISEFALL_ONLY 1 USE_SEPARATE_LIST_FOR_TECH_MIGRATION 0 USE_SINGLE_COMPILER_PASS_PLL_MIF_FILE_WRITER 1 USE_TITAN_IO_BASED_IO_REGISTER_PACKER_UTIL 0 USING_28NM_OR_OLDER_TIMING_METHODOLOGY 1 WYSIWYG_BUS_WIDTH_CHECKING_IN_CUT_ENABLED 1</parameter>
+  <parameter name="deviceFeaturesSystemInfo">ADDRESS_STALL 1 CELL_LEVEL_BACK_ANNOTATION_DISABLED 0 COMPILER_SUPPORT 1 DSP 0 DSP_SHIFTER_BLOCK 0 DUMP_ASM_LAB_BITS_FOR_POWER 1 EMUL 1 ENABLE_ADVANCED_IO_ANALYSIS_GUI_FEATURES 1 EPCS 1 ESB 0 FAKE1 0 FAKE2 0 FAKE3 0 FAMILY_LEVEL_INSTALLATION_ONLY 1 FITTER_USE_FALLING_EDGE_DELAY 0 GENERATE_DC_ON_CURRENT_WARNING_FOR_INTERNAL_CLAMPING_DIODE 0 HARDCOPY 0 HAS_18_BIT_MULTS 0 HAS_ACE_SUPPORT 1 HAS_ADJUSTABLE_OUTPUT_IO_TIMING_MEAS_POINT 0 HAS_ADVANCED_IO_INVERTED_CORNER 0 HAS_ADVANCED_IO_POWER_SUPPORT 1 HAS_ADVANCED_IO_TIMING_SUPPORT 1 HAS_ALM_SUPPORT 0 HAS_ATOM_AND_ROUTING_POWER_MODELED_TOGETHER 0 HAS_AUTO_DERIVE_CLOCK_UNCERTAINTY_SUPPORT 0 HAS_AUTO_FIT_SUPPORT 1 HAS_BALANCED_OPT_TECHNIQUE_SUPPORT 1 HAS_BENEFICIAL_SKEW_SUPPORT 1 HAS_BITLEVEL_DRIVE_STRENGTH_CONTROL 1 HAS_BSDL_FILE_GENERATION 1 HAS_CGA_SUPPORT 1 HAS_CHECK_NETLIST_SUPPORT 0 HAS_CLOCK_REGION_CHECKER_ENABLED 1 HAS_CORE_JUNCTION_TEMP_DERATING 0 HAS_CROSSTALK_SUPPORT 0 HAS_CUSTOM_REGION_SUPPORT 1 HAS_DAP_JTAG_FROM_HPS 0 HAS_DATA_DRIVEN_ACVQ_HSSI_SUPPORT 0 HAS_DDB_FDI_SUPPORT 0 HAS_DESIGN_ANALYZER_SUPPORT 1 HAS_DETAILED_IO_RAIL_POWER_MODEL 1 HAS_DETAILED_LEIM_STATIC_POWER_MODEL 1 HAS_DETAILED_LE_POWER_MODEL 1 HAS_DETAILED_ROUTING_MUX_STATIC_POWER_MODEL 1 HAS_DETAILED_THERMAL_CIRCUIT_PARAMETER_SUPPORT 1 HAS_DEVICE_MIGRATION_SUPPORT 1 HAS_DIAGONAL_MIGRATION_SUPPORT 0 HAS_EMIF_TOOLKIT_SUPPORT 0 HAS_ERROR_DETECTION_SUPPORT 0 HAS_FAMILY_VARIANT_MIGRATION_SUPPORT 0 HAS_FANOUT_FREE_NODE_SUPPORT 1 HAS_FAST_FIT_SUPPORT 1 HAS_FITTER_EARLY_TIMING_ESTIMATE_SUPPORT 1 HAS_FITTER_ECO_SUPPORT 1 HAS_FIT_NETLIST_OPT_RETIME_SUPPORT 1 HAS_FIT_NETLIST_OPT_SUPPORT 1 HAS_FORMAL_VERIFICATION_SUPPORT 1 HAS_FPGA_XCHANGE_SUPPORT 1 HAS_FSAC_LUTRAM_REGISTER_PACKING_SUPPORT 0 HAS_FULL_DAT_MIN_TIMING_SUPPORT 1 HAS_FULL_INCREMENTAL_DESIGN_SUPPORT 1 HAS_FUNCTIONAL_SIMULATION_SUPPORT 1 HAS_FUNCTIONAL_VERILOG_SIMULATION_SUPPORT 0 HAS_FUNCTIONAL_VHDL_SIMULATION_SUPPORT 0 HAS_GLITCH_FILTERING_SUPPORT 1 HAS_HC_READY_SUPPORT 0 HAS_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_HOLD_TIME_AVOIDANCE_ACROSS_CLOCK_SPINE_SUPPORT 1 HAS_HSPICE_WRITER_SUPPORT 1 HAS_HSSI_POWER_CALCULATOR 0 HAS_IBISO_WRITER_SUPPORT 0 HAS_INCREMENTAL_DAT_SUPPORT 1 HAS_INCREMENTAL_SYNTHESIS_SUPPORT 1 HAS_INTERFACE_PLANNER_SUPPORT 0 HAS_IO_ASSIGNMENT_ANALYSIS_SUPPORT 1 HAS_IO_DECODER 0 HAS_IO_PLACEMENT_OPTIMIZATION_SUPPORT 1 HAS_IO_SMART_RECOMPILE_SUPPORT 0 HAS_JITTER_SUPPORT 1 HAS_JTAG_SLD_HUB_SUPPORT 1 HAS_LIMITED_TCL_FITTER_SUPPORT 0 HAS_LOGIC_LOCK_SUPPORT 1 HAS_MICROPROCESSOR 0 HAS_MIF_SMART_COMPILE_SUPPORT 1 HAS_MINMAX_TIMING_MODELING_SUPPORT 1 HAS_MIN_TIMING_ANALYSIS_SUPPORT 1 HAS_MUX_RESTRUCTURE_SUPPORT 1 HAS_NEW_HC_FLOW_SUPPORT 0 HAS_NEW_SERDES_MAX_RESOURCE_COUNT_REPORTING_SUPPORT 1 HAS_NEW_VPR_SUPPORT 1 HAS_NONSOCKET_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_NO_HARDBLOCK_PARTITION_SUPPORT 0 HAS_NO_JTAG_USERCODE_SUPPORT 0 HAS_OPERATING_SETTINGS_AND_CONDITIONS_REPORTING_SUPPORT 1 HAS_PAD_LOCATION_ASSIGNMENT_SUPPORT 0 HAS_PARTIAL_RECONFIG_SUPPORT 0 HAS_PHYSICAL_NETLIST_OUTPUT 0 HAS_PHYSICAL_ROUTING_SUPPORT 0 HAS_PIN_SPECIFIC_VOLTAGE_SUPPORT 1 HAS_PLDM_REF_SUPPORT 1 HAS_POWER_ESTIMATION_SUPPORT 1 HAS_PRELIMINARY_CLOCK_UNCERTAINTY_NUMBERS 0 HAS_PRE_FITTER_FPP_SUPPORT 0 HAS_PRE_FITTER_LUTRAM_NETLIST_CHECKER_ENABLED 0 HAS_PVA_SUPPORT 1 HAS_RCF_SUPPORT 1 HAS_RCF_SUPPORT_FOR_DEBUGGING 0 HAS_RED_BLACK_SEPARATION_SUPPORT 0 HAS_RE_LEVEL_TIMING_GRAPH_SUPPORT 1 HAS_RISEFALL_DELAY_SUPPORT 1 HAS_SIGNAL_PROBE_SUPPORT 1 HAS_SIGNAL_TAP_SUPPORT 1 HAS_SIMULATOR_SUPPORT 0 HAS_SPLIT_IO_SUPPORT 1 HAS_SPLIT_LC_SUPPORT 1 HAS_SYNTH_FSYN_NETLIST_OPT_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_RETIME_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_SUPPORT 1 HAS_TCL_FITTER_SUPPORT 0 HAS_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_TEMPLATED_REGISTER_PACKING_SUPPORT 1 HAS_TIME_BORROWING_SUPPORT 0 HAS_TIMING_DRIVEN_SYNTHESIS_SUPPORT 1 HAS_TIMING_INFO_SUPPORT 1 HAS_TIMING_OPERATING_CONDITIONS 1 HAS_TIMING_SIMULATION_SUPPORT 1 HAS_TITAN_BASED_MAC_REGISTER_PACKER_SUPPORT 0 HAS_U2B2_SUPPORT 0 HAS_USER_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_USE_FITTER_INFO_SUPPORT 1 HAS_VCCPD_POWER_RAIL 0 HAS_VERTICAL_MIGRATION_SUPPORT 1 HAS_VIEWDRAW_SYMBOL_SUPPORT 0 HAS_VIO_SUPPORT 1 HAS_VIRTUAL_DEVICES 0 HAS_WYSIWYG_DFFEAS_SUPPORT 1 HAS_XIBISO_WRITER_SUPPORT 1 IFP_USE_LEGACY_IO_CHECKER 0 INCREMENTAL_DESIGN_SUPPORTS_COMPATIBLE_CONSTRAINTS 1 INSTALLED 0 IS_CONFIG_ROM 0 IS_DEFAULT_FAMILY 0 IS_HARDCOPY_FAMILY 0 LVDS_IO 1 M10K_MEMORY 0 M144K_MEMORY 0 M20K_MEMORY 0 M4K_MEMORY 0 M512_MEMORY 0 M9K_MEMORY 1 MLAB_MEMORY 0 MRAM_MEMORY 0 NOT_LISTED 0 NO_RPE_SUPPORT 0 NO_SUPPORT_FOR_LOGICLOCK_CONTENT_BACK_ANNOTATION 1 NO_SUPPORT_FOR_STA_CLOCK_UNCERTAINTY_CHECK 0 NO_TDC_SUPPORT 0 POSTFIT_BAK_DATABASE_EXPORT_ENABLED 1 POSTMAP_BAK_DATABASE_EXPORT_ENABLED 1 PROGRAMMER_SUPPORT 1 QFIT_IN_DEVELOPMENT 0 QMAP_IN_DEVELOPMENT 0 RAM_LOGICAL_NAME_CHECKING_IN_CUT_ENABLED 1 REPORTS_METASTABILITY_MTBF 1 REQUIRES_INSTALLATION_PATCH 0 REQUIRES_LIST_OF_TEMPERATURE_AND_VOLTAGE_OPERATING_CONDITIONS 1 RESERVES_SIGNAL_PROBE_PINS 0 RESOLVE_MAX_FANOUT_EARLY 1 RESOLVE_MAX_FANOUT_LATE 0 RESPECTS_FIXED_SIZED_LOCKED_LOCATION_LOGICLOCK 1 RESTRICTED_USER_SELECTION 0 RISEFALL_SUPPORT_IS_HIDDEN 0 STRICT_TIMING_DB_CHECKS 0 SUPPORTS_ADDITIONAL_OPTIONS_FOR_UNUSED_IO 0 SUPPORTS_CRC 1 SUPPORTS_DIFFERENTIAL_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_DSP_BALANCING_BACK_ANNOTATION 0 SUPPORTS_GENERATION_OF_EARLY_POWER_ESTIMATOR_FILE 1 SUPPORTS_GLOBAL_SIGNAL_BACK_ANNOTATION 0 SUPPORTS_MAC_CHAIN_OUT_ADDER 0 SUPPORTS_RAM_PACKING_BACK_ANNOTATION 0 SUPPORTS_REG_PACKING_BACK_ANNOTATION 0 SUPPORTS_SIGNALPROBE_REGISTER_PIPELINING 1 SUPPORTS_SINGLE_ENDED_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_USER_MANUAL_LOGIC_DUPLICATION 1 TMV_RUN_CUSTOMIZABLE_VIEWER 1 TMV_RUN_INTERNAL_DETAILS 1 TMV_RUN_INTERNAL_DETAILS_ON_IO 0 TMV_RUN_INTERNAL_DETAILS_ON_IOBUF 1 TMV_RUN_INTERNAL_DETAILS_ON_LCELL 0 TMV_RUN_INTERNAL_DETAILS_ON_LRAM 0 TRANSCEIVER_3G_BLOCK 0 TRANSCEIVER_6G_BLOCK 0 USES_ACV_FOR_FLED 1 USES_ADB_FOR_BACK_ANNOTATION 1 USES_ALTERA_LNSIM 0 USES_ASIC_ROUTING_POWER_CALCULATOR 0 USES_DATA_DRIVEN_PLL_COMPUTATION_UTIL 1 USES_DEV 1 USES_ICP_FOR_ECO_FITTER 0 USES_LIBERTY_TIMING 0 USES_POWER_SIGNAL_ACTIVITIES 1 USES_THIRD_GENERATION_TIMING_MODELS_TIS 1 USES_U2B2_TIMING_MODELS 0 USE_ADVANCED_IO_POWER_BY_DEFAULT 1 USE_ADVANCED_IO_TIMING_BY_DEFAULT 1 USE_BASE_FAMILY_DDB_PATH 0 USE_OCT_AUTO_CALIBRATION 1 USE_RELAX_IO_ASSIGNMENT_RULES 0 USE_RISEFALL_ONLY 1 USE_SEPARATE_LIST_FOR_TECH_MIGRATION 0 USE_SINGLE_COMPILER_PASS_PLL_MIF_FILE_WRITER 1 USE_TITAN_IO_BASED_IO_REGISTER_PACKER_UTIL 0 WYSIWYG_BUS_WIDTH_CHECKING_IN_CUT_ENABLED 1</parameter>
   <parameter name="tightlyCoupledDataMaster0MapParam" value="" />
   <parameter name="tightlyCoupledDataMaster1MapParam" value="" />
   <parameter name="tightlyCoupledDataMaster2MapParam" value="" />
@@ -371,7 +362,11 @@
   <parameter name="tightlyCoupledInstructionMaster2MapParam" value="" />
   <parameter name="tightlyCoupledInstructionMaster3MapParam" value="" />
  </module>
- <module kind="altera_avalon_spi" version="13.1" enabled="1" name="spi_0">
+ <module
+   kind="altera_avalon_spi"
+   version="13.0.1.99.2"
+   enabled="1"
+   name="spi_0">
   <parameter name="clockPhase" value="0" />
   <parameter name="clockPolarity" value="0" />
   <parameter name="dataWidth" value="8" />
@@ -389,7 +384,7 @@
  </module>
  <module
    kind="altera_avalon_jtag_uart"
-   version="13.1"
+   version="13.0.1.99.2"
    enabled="1"
    name="jtag_uart_0">
   <parameter name="allowMultipleConnections" value="false" />
@@ -407,7 +402,7 @@
  </module>
  <module
    kind="altera_avalon_onchip_memory2"
-   version="13.1"
+   version="13.0.1.99.2"
    enabled="1"
    name="onchip_memory2_0">
   <parameter name="allowInSystemMemoryContentEditor" value="true" />
@@ -427,12 +422,15 @@
   <parameter name="useNonDefaultInitFile" value="false" />
   <parameter name="useShallowMemBlocks" value="false" />
   <parameter name="writable" value="true" />
-  <parameter name="ecc_enabled" value="false" />
-  <parameter name="autoInitializationFileName">nios_system_onchip_memory2_0</parameter>
+  <parameter name="autoInitializationFileName">$${FILENAME}_onchip_memory2_0</parameter>
   <parameter name="deviceFamily" value="Cyclone IV E" />
-  <parameter name="deviceFeatures">ADDRESS_STALL 1 ADVANCED_INFO 0 ANY_QFP 0 CELL_LEVEL_BACK_ANNOTATION_DISABLED 0 COMPILER_SUPPORT 1 DSP 0 DSP_SHIFTER_BLOCK 0 DUMP_ASM_LAB_BITS_FOR_POWER 1 EMUL 1 ENABLE_ADVANCED_IO_ANALYSIS_GUI_FEATURES 1 ENABLE_PIN_PLANNER 0 ENGINEERING_SAMPLE 0 EPCS 1 ESB 0 FAKE1 0 FAKE2 0 FAKE3 0 FAMILY_LEVEL_INSTALLATION_ONLY 1 FASTEST 0 FINAL_TIMING_MODEL 0 FITTER_USE_FALLING_EDGE_DELAY 0 GENERATE_DC_ON_CURRENT_WARNING_FOR_INTERNAL_CLAMPING_DIODE 0 HARDCOPY 0 HAS_18_BIT_MULTS 0 HAS_ACE_SUPPORT 1 HAS_ACTIVE_PARALLEL_FLASH_SUPPORT 0 HAS_ADJUSTABLE_OUTPUT_IO_TIMING_MEAS_POINT 0 HAS_ADVANCED_IO_INVERTED_CORNER 0 HAS_ADVANCED_IO_POWER_SUPPORT 1 HAS_ADVANCED_IO_TIMING_SUPPORT 1 HAS_ALM_SUPPORT 0 HAS_ATOM_AND_ROUTING_POWER_MODELED_TOGETHER 0 HAS_AUTO_DERIVE_CLOCK_UNCERTAINTY_SUPPORT 0 HAS_AUTO_FIT_SUPPORT 1 HAS_BALANCED_OPT_TECHNIQUE_SUPPORT 1 HAS_BENEFICIAL_SKEW_SUPPORT 1 HAS_BITLEVEL_DRIVE_STRENGTH_CONTROL 1 HAS_BSDL_FILE_GENERATION 1 HAS_CDB_RE_NETWORK_PRESERVATION_SUPPORT 0 HAS_CGA_SUPPORT 1 HAS_CHECK_NETLIST_SUPPORT 0 HAS_CLOCK_REGION_CHECKER_ENABLED 1 HAS_CORE_JUNCTION_TEMP_DERATING 0 HAS_CROSSTALK_SUPPORT 0 HAS_CUSTOM_REGION_SUPPORT 1 HAS_DAP_JTAG_FROM_HPS 0 HAS_DATA_DRIVEN_ACVQ_HSSI_SUPPORT 0 HAS_DDB_FDI_SUPPORT 0 HAS_DESIGN_ANALYZER_SUPPORT 1 HAS_DETAILED_IO_RAIL_POWER_MODEL 1 HAS_DETAILED_LEIM_STATIC_POWER_MODEL 1 HAS_DETAILED_LE_POWER_MODEL 1 HAS_DETAILED_ROUTING_MUX_STATIC_POWER_MODEL 1 HAS_DETAILED_THERMAL_CIRCUIT_PARAMETER_SUPPORT 1 HAS_DEVICE_MIGRATION_SUPPORT 1 HAS_DIAGONAL_MIGRATION_SUPPORT 0 HAS_EMIF_TOOLKIT_SUPPORT 0 HAS_ERROR_DETECTION_SUPPORT 0 HAS_FAMILY_VARIANT_MIGRATION_SUPPORT 0 HAS_FANOUT_FREE_NODE_SUPPORT 1 HAS_FAST_FIT_SUPPORT 1 HAS_FITTER_EARLY_TIMING_ESTIMATE_SUPPORT 1 HAS_FITTER_ECO_SUPPORT 1 HAS_FIT_NETLIST_OPT_RETIME_SUPPORT 1 HAS_FIT_NETLIST_OPT_SUPPORT 1 HAS_FORMAL_VERIFICATION_SUPPORT 1 HAS_FPGA_XCHANGE_SUPPORT 1 HAS_FSAC_LUTRAM_REGISTER_PACKING_SUPPORT 0 HAS_FULL_DAT_MIN_TIMING_SUPPORT 1 HAS_FULL_INCREMENTAL_DESIGN_SUPPORT 1 HAS_FUNCTIONAL_SIMULATION_SUPPORT 1 HAS_FUNCTIONAL_VERILOG_SIMULATION_SUPPORT 0 HAS_FUNCTIONAL_VHDL_SIMULATION_SUPPORT 0 HAS_GLITCH_FILTERING_SUPPORT 1 HAS_HARDCOPYII_SUPPORT 0 HAS_HC_READY_SUPPORT 0 HAS_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_HOLD_TIME_AVOIDANCE_ACROSS_CLOCK_SPINE_SUPPORT 1 HAS_HSPICE_WRITER_SUPPORT 1 HAS_HSSI_POWER_CALCULATOR 0 HAS_IBISO_WRITER_SUPPORT 0 HAS_ICD_DATA_IP 0 HAS_INCREMENTAL_DAT_SUPPORT 1 HAS_INCREMENTAL_SYNTHESIS_SUPPORT 1 HAS_INTERFACE_PLANNER_SUPPORT 0 HAS_IO_ASSIGNMENT_ANALYSIS_SUPPORT 1 HAS_IO_DECODER 0 HAS_IO_PLACEMENT_OPTIMIZATION_SUPPORT 1 HAS_IO_SMART_RECOMPILE_SUPPORT 0 HAS_JITTER_SUPPORT 1 HAS_JTAG_SLD_HUB_SUPPORT 1 HAS_LIMITED_TCL_FITTER_SUPPORT 0 HAS_LOGICAL_FLOORPLANNER_SUPPORT 0 HAS_LOGIC_LOCK_SUPPORT 1 HAS_MICROPROCESSOR 0 HAS_MIF_SMART_COMPILE_SUPPORT 1 HAS_MINMAX_TIMING_MODELING_SUPPORT 1 HAS_MIN_TIMING_ANALYSIS_SUPPORT 1 HAS_MUX_RESTRUCTURE_SUPPORT 1 HAS_NEW_HC_FLOW_SUPPORT 0 HAS_NEW_SERDES_MAX_RESOURCE_COUNT_REPORTING_SUPPORT 1 HAS_NEW_VPR_SUPPORT 1 HAS_NONSOCKET_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_NO_HARDBLOCK_PARTITION_SUPPORT 0 HAS_NO_JTAG_USERCODE_SUPPORT 0 HAS_OPERATING_SETTINGS_AND_CONDITIONS_REPORTING_SUPPORT 1 HAS_PAD_LOCATION_ASSIGNMENT_SUPPORT 0 HAS_PARTIAL_RECONFIG_SUPPORT 0 HAS_PASSIVE_PARALLEL_SUPPORT 0 HAS_PHYSICAL_NETLIST_OUTPUT 0 HAS_PHYSICAL_ROUTING_SUPPORT 0 HAS_PIN_SPECIFIC_VOLTAGE_SUPPORT 1 HAS_PLDM_REF_SUPPORT 1 HAS_POWER_BINNING_LIMITS_DATA 0 HAS_POWER_ESTIMATION_SUPPORT 1 HAS_PRELIMINARY_CLOCK_UNCERTAINTY_NUMBERS 0 HAS_PRE_FITTER_FPP_SUPPORT 0 HAS_PRE_FITTER_LUTRAM_NETLIST_CHECKER_ENABLED 0 HAS_PVA_SUPPORT 1 HAS_RAPID_RECOMPILE_SUPPORT 0 HAS_RCF_SUPPORT 1 HAS_RCF_SUPPORT_FOR_DEBUGGING 0 HAS_RED_BLACK_SEPARATION_SUPPORT 0 HAS_RE_LEVEL_TIMING_GRAPH_SUPPORT 1 HAS_RISEFALL_DELAY_SUPPORT 1 HAS_SIGNAL_PROBE_SUPPORT 1 HAS_SIGNAL_TAP_SUPPORT 1 HAS_SIMULATOR_SUPPORT 0 HAS_SPLIT_IO_SUPPORT 1 HAS_SPLIT_LC_SUPPORT 1 HAS_STRICT_PRESERVATION_SUPPORT 1 HAS_SYNTH_FSYN_NETLIST_OPT_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_RETIME_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_SUPPORT 1 HAS_TCL_FITTER_SUPPORT 0 HAS_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_TEMPLATED_REGISTER_PACKING_SUPPORT 1 HAS_TIME_BORROWING_SUPPORT 0 HAS_TIMING_DRIVEN_SYNTHESIS_SUPPORT 1 HAS_TIMING_INFO_SUPPORT 1 HAS_TIMING_OPERATING_CONDITIONS 1 HAS_TIMING_SIMULATION_SUPPORT 1 HAS_TITAN_BASED_MAC_REGISTER_PACKER_SUPPORT 0 HAS_U2B2_SUPPORT 0 HAS_USER_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_USE_FITTER_INFO_SUPPORT 1 HAS_VCCPD_POWER_RAIL 0 HAS_VERTICAL_MIGRATION_SUPPORT 1 HAS_VIEWDRAW_SYMBOL_SUPPORT 0 HAS_VIO_SUPPORT 1 HAS_VIRTUAL_DEVICES 0 HAS_WYSIWYG_DFFEAS_SUPPORT 1 HAS_XIBISO_WRITER_SUPPORT 1 IFP_USE_LEGACY_IO_CHECKER 0 INCREMENTAL_DESIGN_SUPPORTS_COMPATIBLE_CONSTRAINTS 1 INSTALLED 0 INTERNAL_POF_SUPPORT_ENABLED 0 INTERNAL_USE_ONLY 0 ISSUE_MILITARY_TEMPERATURE_WARNING 0 IS_CONFIG_ROM 0 IS_DEFAULT_FAMILY 0 IS_HARDCOPY_FAMILY 0 IS_HBGA_PACKAGE 0 IS_HIGH_CURRENT_PART 0 IS_LOW_POWER_PART 0 IS_SDM_ONLY_PACKAGE 0 LVDS_IO 1 M10K_MEMORY 0 M144K_MEMORY 0 M20K_MEMORY 0 M4K_MEMORY 0 M512_MEMORY 0 M9K_MEMORY 1 MLAB_MEMORY 0 MRAM_MEMORY 0 NOT_LISTED 0 NOT_MIGRATABLE 0 NO_FITTER_DELAY_CACHE_GENERATED 0 NO_PIN_OUT 0 NO_POF 0 NO_RPE_SUPPORT 0 NO_SUPPORT_FOR_LOGICLOCK_CONTENT_BACK_ANNOTATION 1 NO_SUPPORT_FOR_STA_CLOCK_UNCERTAINTY_CHECK 0 NO_TDC_SUPPORT 0 POSTFIT_BAK_DATABASE_EXPORT_ENABLED 1 POSTMAP_BAK_DATABASE_EXPORT_ENABLED 1 PROGRAMMER_SUPPORT 1 QFIT_IN_DEVELOPMENT 0 QMAP_IN_DEVELOPMENT 0 RAM_LOGICAL_NAME_CHECKING_IN_CUT_ENABLED 1 REPORTS_METASTABILITY_MTBF 1 REQUIRES_INSTALLATION_PATCH 0 REQUIRES_LIST_OF_TEMPERATURE_AND_VOLTAGE_OPERATING_CONDITIONS 1 RESERVES_SIGNAL_PROBE_PINS 0 RESOLVE_MAX_FANOUT_EARLY 1 RESOLVE_MAX_FANOUT_LATE 0 RESPECTS_FIXED_SIZED_LOCKED_LOCATION_LOGICLOCK 1 RESTRICTED_USER_SELECTION 0 RISEFALL_SUPPORT_IS_HIDDEN 0 SHOW_HIDDEN_FAMILY_IN_PROGRAMMER 0 STRICT_TIMING_DB_CHECKS 0 SUPPORTS_ADDITIONAL_OPTIONS_FOR_UNUSED_IO 0 SUPPORTS_CRC 1 SUPPORTS_DIFFERENTIAL_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_DSP_BALANCING_BACK_ANNOTATION 0 SUPPORTS_GENERATION_OF_EARLY_POWER_ESTIMATOR_FILE 1 SUPPORTS_GLOBAL_SIGNAL_BACK_ANNOTATION 0 SUPPORTS_MAC_CHAIN_OUT_ADDER 0 SUPPORTS_RAM_PACKING_BACK_ANNOTATION 0 SUPPORTS_REG_PACKING_BACK_ANNOTATION 0 SUPPORTS_SIGNALPROBE_REGISTER_PIPELINING 1 SUPPORTS_SINGLE_ENDED_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_USER_MANUAL_LOGIC_DUPLICATION 1 TMV_RUN_CUSTOMIZABLE_VIEWER 1 TMV_RUN_INTERNAL_DETAILS 1 TMV_RUN_INTERNAL_DETAILS_ON_IO 0 TMV_RUN_INTERNAL_DETAILS_ON_IOBUF 1 TMV_RUN_INTERNAL_DETAILS_ON_LCELL 0 TMV_RUN_INTERNAL_DETAILS_ON_LRAM 0 TRANSCEIVER_3G_BLOCK 0 TRANSCEIVER_6G_BLOCK 0 USES_ACV_FOR_FLED 1 USES_ADB_FOR_BACK_ANNOTATION 1 USES_ALTERA_LNSIM 0 USES_ASIC_ROUTING_POWER_CALCULATOR 0 USES_DATA_DRIVEN_PLL_COMPUTATION_UTIL 1 USES_DEV 1 USES_ICP_FOR_ECO_FITTER 0 USES_LIBERTY_TIMING 0 USES_POWER_SIGNAL_ACTIVITIES 1 USES_THIRD_GENERATION_TIMING_MODELS_TIS 1 USES_U2B2_TIMING_MODELS 0 USE_ADVANCED_IO_POWER_BY_DEFAULT 1 USE_ADVANCED_IO_TIMING_BY_DEFAULT 1 USE_BASE_FAMILY_DDB_PATH 0 USE_OCT_AUTO_CALIBRATION 1 USE_RELAX_IO_ASSIGNMENT_RULES 0 USE_RISEFALL_ONLY 1 USE_SEPARATE_LIST_FOR_TECH_MIGRATION 0 USE_SINGLE_COMPILER_PASS_PLL_MIF_FILE_WRITER 1 USE_TITAN_IO_BASED_IO_REGISTER_PACKER_UTIL 0 USING_28NM_OR_OLDER_TIMING_METHODOLOGY 1 WYSIWYG_BUS_WIDTH_CHECKING_IN_CUT_ENABLED 1</parameter>
+  <parameter name="deviceFeatures">ADDRESS_STALL 1 CELL_LEVEL_BACK_ANNOTATION_DISABLED 0 COMPILER_SUPPORT 1 DSP 0 DSP_SHIFTER_BLOCK 0 DUMP_ASM_LAB_BITS_FOR_POWER 1 EMUL 1 ENABLE_ADVANCED_IO_ANALYSIS_GUI_FEATURES 1 EPCS 1 ESB 0 FAKE1 0 FAKE2 0 FAKE3 0 FAMILY_LEVEL_INSTALLATION_ONLY 1 FITTER_USE_FALLING_EDGE_DELAY 0 GENERATE_DC_ON_CURRENT_WARNING_FOR_INTERNAL_CLAMPING_DIODE 0 HARDCOPY 0 HAS_18_BIT_MULTS 0 HAS_ACE_SUPPORT 1 HAS_ADJUSTABLE_OUTPUT_IO_TIMING_MEAS_POINT 0 HAS_ADVANCED_IO_INVERTED_CORNER 0 HAS_ADVANCED_IO_POWER_SUPPORT 1 HAS_ADVANCED_IO_TIMING_SUPPORT 1 HAS_ALM_SUPPORT 0 HAS_ATOM_AND_ROUTING_POWER_MODELED_TOGETHER 0 HAS_AUTO_DERIVE_CLOCK_UNCERTAINTY_SUPPORT 0 HAS_AUTO_FIT_SUPPORT 1 HAS_BALANCED_OPT_TECHNIQUE_SUPPORT 1 HAS_BENEFICIAL_SKEW_SUPPORT 1 HAS_BITLEVEL_DRIVE_STRENGTH_CONTROL 1 HAS_BSDL_FILE_GENERATION 1 HAS_CGA_SUPPORT 1 HAS_CHECK_NETLIST_SUPPORT 0 HAS_CLOCK_REGION_CHECKER_ENABLED 1 HAS_CORE_JUNCTION_TEMP_DERATING 0 HAS_CROSSTALK_SUPPORT 0 HAS_CUSTOM_REGION_SUPPORT 1 HAS_DAP_JTAG_FROM_HPS 0 HAS_DATA_DRIVEN_ACVQ_HSSI_SUPPORT 0 HAS_DDB_FDI_SUPPORT 0 HAS_DESIGN_ANALYZER_SUPPORT 1 HAS_DETAILED_IO_RAIL_POWER_MODEL 1 HAS_DETAILED_LEIM_STATIC_POWER_MODEL 1 HAS_DETAILED_LE_POWER_MODEL 1 HAS_DETAILED_ROUTING_MUX_STATIC_POWER_MODEL 1 HAS_DETAILED_THERMAL_CIRCUIT_PARAMETER_SUPPORT 1 HAS_DEVICE_MIGRATION_SUPPORT 1 HAS_DIAGONAL_MIGRATION_SUPPORT 0 HAS_EMIF_TOOLKIT_SUPPORT 0 HAS_ERROR_DETECTION_SUPPORT 0 HAS_FAMILY_VARIANT_MIGRATION_SUPPORT 0 HAS_FANOUT_FREE_NODE_SUPPORT 1 HAS_FAST_FIT_SUPPORT 1 HAS_FITTER_EARLY_TIMING_ESTIMATE_SUPPORT 1 HAS_FITTER_ECO_SUPPORT 1 HAS_FIT_NETLIST_OPT_RETIME_SUPPORT 1 HAS_FIT_NETLIST_OPT_SUPPORT 1 HAS_FORMAL_VERIFICATION_SUPPORT 1 HAS_FPGA_XCHANGE_SUPPORT 1 HAS_FSAC_LUTRAM_REGISTER_PACKING_SUPPORT 0 HAS_FULL_DAT_MIN_TIMING_SUPPORT 1 HAS_FULL_INCREMENTAL_DESIGN_SUPPORT 1 HAS_FUNCTIONAL_SIMULATION_SUPPORT 1 HAS_FUNCTIONAL_VERILOG_SIMULATION_SUPPORT 0 HAS_FUNCTIONAL_VHDL_SIMULATION_SUPPORT 0 HAS_GLITCH_FILTERING_SUPPORT 1 HAS_HC_READY_SUPPORT 0 HAS_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_HOLD_TIME_AVOIDANCE_ACROSS_CLOCK_SPINE_SUPPORT 1 HAS_HSPICE_WRITER_SUPPORT 1 HAS_HSSI_POWER_CALCULATOR 0 HAS_IBISO_WRITER_SUPPORT 0 HAS_INCREMENTAL_DAT_SUPPORT 1 HAS_INCREMENTAL_SYNTHESIS_SUPPORT 1 HAS_INTERFACE_PLANNER_SUPPORT 0 HAS_IO_ASSIGNMENT_ANALYSIS_SUPPORT 1 HAS_IO_DECODER 0 HAS_IO_PLACEMENT_OPTIMIZATION_SUPPORT 1 HAS_IO_SMART_RECOMPILE_SUPPORT 0 HAS_JITTER_SUPPORT 1 HAS_JTAG_SLD_HUB_SUPPORT 1 HAS_LIMITED_TCL_FITTER_SUPPORT 0 HAS_LOGIC_LOCK_SUPPORT 1 HAS_MICROPROCESSOR 0 HAS_MIF_SMART_COMPILE_SUPPORT 1 HAS_MINMAX_TIMING_MODELING_SUPPORT 1 HAS_MIN_TIMING_ANALYSIS_SUPPORT 1 HAS_MUX_RESTRUCTURE_SUPPORT 1 HAS_NEW_HC_FLOW_SUPPORT 0 HAS_NEW_SERDES_MAX_RESOURCE_COUNT_REPORTING_SUPPORT 1 HAS_NEW_VPR_SUPPORT 1 HAS_NONSOCKET_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_NO_HARDBLOCK_PARTITION_SUPPORT 0 HAS_NO_JTAG_USERCODE_SUPPORT 0 HAS_OPERATING_SETTINGS_AND_CONDITIONS_REPORTING_SUPPORT 1 HAS_PAD_LOCATION_ASSIGNMENT_SUPPORT 0 HAS_PARTIAL_RECONFIG_SUPPORT 0 HAS_PHYSICAL_NETLIST_OUTPUT 0 HAS_PHYSICAL_ROUTING_SUPPORT 0 HAS_PIN_SPECIFIC_VOLTAGE_SUPPORT 1 HAS_PLDM_REF_SUPPORT 1 HAS_POWER_ESTIMATION_SUPPORT 1 HAS_PRELIMINARY_CLOCK_UNCERTAINTY_NUMBERS 0 HAS_PRE_FITTER_FPP_SUPPORT 0 HAS_PRE_FITTER_LUTRAM_NETLIST_CHECKER_ENABLED 0 HAS_PVA_SUPPORT 1 HAS_RCF_SUPPORT 1 HAS_RCF_SUPPORT_FOR_DEBUGGING 0 HAS_RED_BLACK_SEPARATION_SUPPORT 0 HAS_RE_LEVEL_TIMING_GRAPH_SUPPORT 1 HAS_RISEFALL_DELAY_SUPPORT 1 HAS_SIGNAL_PROBE_SUPPORT 1 HAS_SIGNAL_TAP_SUPPORT 1 HAS_SIMULATOR_SUPPORT 0 HAS_SPLIT_IO_SUPPORT 1 HAS_SPLIT_LC_SUPPORT 1 HAS_SYNTH_FSYN_NETLIST_OPT_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_RETIME_SUPPORT 1 HAS_SYNTH_NETLIST_OPT_SUPPORT 1 HAS_TCL_FITTER_SUPPORT 0 HAS_TECHNOLOGY_MIGRATION_SUPPORT 0 HAS_TEMPLATED_REGISTER_PACKING_SUPPORT 1 HAS_TIME_BORROWING_SUPPORT 0 HAS_TIMING_DRIVEN_SYNTHESIS_SUPPORT 1 HAS_TIMING_INFO_SUPPORT 1 HAS_TIMING_OPERATING_CONDITIONS 1 HAS_TIMING_SIMULATION_SUPPORT 1 HAS_TITAN_BASED_MAC_REGISTER_PACKER_SUPPORT 0 HAS_U2B2_SUPPORT 0 HAS_USER_HIGH_SPEED_LOW_POWER_TILE_SUPPORT 0 HAS_USE_FITTER_INFO_SUPPORT 1 HAS_VCCPD_POWER_RAIL 0 HAS_VERTICAL_MIGRATION_SUPPORT 1 HAS_VIEWDRAW_SYMBOL_SUPPORT 0 HAS_VIO_SUPPORT 1 HAS_VIRTUAL_DEVICES 0 HAS_WYSIWYG_DFFEAS_SUPPORT 1 HAS_XIBISO_WRITER_SUPPORT 1 IFP_USE_LEGACY_IO_CHECKER 0 INCREMENTAL_DESIGN_SUPPORTS_COMPATIBLE_CONSTRAINTS 1 INSTALLED 0 IS_CONFIG_ROM 0 IS_DEFAULT_FAMILY 0 IS_HARDCOPY_FAMILY 0 LVDS_IO 1 M10K_MEMORY 0 M144K_MEMORY 0 M20K_MEMORY 0 M4K_MEMORY 0 M512_MEMORY 0 M9K_MEMORY 1 MLAB_MEMORY 0 MRAM_MEMORY 0 NOT_LISTED 0 NO_RPE_SUPPORT 0 NO_SUPPORT_FOR_LOGICLOCK_CONTENT_BACK_ANNOTATION 1 NO_SUPPORT_FOR_STA_CLOCK_UNCERTAINTY_CHECK 0 NO_TDC_SUPPORT 0 POSTFIT_BAK_DATABASE_EXPORT_ENABLED 1 POSTMAP_BAK_DATABASE_EXPORT_ENABLED 1 PROGRAMMER_SUPPORT 1 QFIT_IN_DEVELOPMENT 0 QMAP_IN_DEVELOPMENT 0 RAM_LOGICAL_NAME_CHECKING_IN_CUT_ENABLED 1 REPORTS_METASTABILITY_MTBF 1 REQUIRES_INSTALLATION_PATCH 0 REQUIRES_LIST_OF_TEMPERATURE_AND_VOLTAGE_OPERATING_CONDITIONS 1 RESERVES_SIGNAL_PROBE_PINS 0 RESOLVE_MAX_FANOUT_EARLY 1 RESOLVE_MAX_FANOUT_LATE 0 RESPECTS_FIXED_SIZED_LOCKED_LOCATION_LOGICLOCK 1 RESTRICTED_USER_SELECTION 0 RISEFALL_SUPPORT_IS_HIDDEN 0 STRICT_TIMING_DB_CHECKS 0 SUPPORTS_ADDITIONAL_OPTIONS_FOR_UNUSED_IO 0 SUPPORTS_CRC 1 SUPPORTS_DIFFERENTIAL_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_DSP_BALANCING_BACK_ANNOTATION 0 SUPPORTS_GENERATION_OF_EARLY_POWER_ESTIMATOR_FILE 1 SUPPORTS_GLOBAL_SIGNAL_BACK_ANNOTATION 0 SUPPORTS_MAC_CHAIN_OUT_ADDER 0 SUPPORTS_RAM_PACKING_BACK_ANNOTATION 0 SUPPORTS_REG_PACKING_BACK_ANNOTATION 0 SUPPORTS_SIGNALPROBE_REGISTER_PIPELINING 1 SUPPORTS_SINGLE_ENDED_AIOT_BOARD_TRACE_MODEL 1 SUPPORTS_USER_MANUAL_LOGIC_DUPLICATION 1 TMV_RUN_CUSTOMIZABLE_VIEWER 1 TMV_RUN_INTERNAL_DETAILS 1 TMV_RUN_INTERNAL_DETAILS_ON_IO 0 TMV_RUN_INTERNAL_DETAILS_ON_IOBUF 1 TMV_RUN_INTERNAL_DETAILS_ON_LCELL 0 TMV_RUN_INTERNAL_DETAILS_ON_LRAM 0 TRANSCEIVER_3G_BLOCK 0 TRANSCEIVER_6G_BLOCK 0 USES_ACV_FOR_FLED 1 USES_ADB_FOR_BACK_ANNOTATION 1 USES_ALTERA_LNSIM 0 USES_ASIC_ROUTING_POWER_CALCULATOR 0 USES_DATA_DRIVEN_PLL_COMPUTATION_UTIL 1 USES_DEV 1 USES_ICP_FOR_ECO_FITTER 0 USES_LIBERTY_TIMING 0 USES_POWER_SIGNAL_ACTIVITIES 1 USES_THIRD_GENERATION_TIMING_MODELS_TIS 1 USES_U2B2_TIMING_MODELS 0 USE_ADVANCED_IO_POWER_BY_DEFAULT 1 USE_ADVANCED_IO_TIMING_BY_DEFAULT 1 USE_BASE_FAMILY_DDB_PATH 0 USE_OCT_AUTO_CALIBRATION 1 USE_RELAX_IO_ASSIGNMENT_RULES 0 USE_RISEFALL_ONLY 1 USE_SEPARATE_LIST_FOR_TECH_MIGRATION 0 USE_SINGLE_COMPILER_PASS_PLL_MIF_FILE_WRITER 1 USE_TITAN_IO_BASED_IO_REGISTER_PACKER_UTIL 0 WYSIWYG_BUS_WIDTH_CHECKING_IN_CUT_ENABLED 1</parameter>
  </module>
- <module kind="altera_avalon_timer" version="13.1" enabled="1" name="timer_0">
+ <module
+   kind="altera_avalon_timer"
+   version="13.0.1.99.2"
+   enabled="1"
+   name="timer_0">
   <parameter name="alwaysRun" value="false" />
   <parameter name="counterSize" value="64" />
   <parameter name="fixedPeriod" value="false" />
@@ -443,7 +441,11 @@
   <parameter name="timeoutPulseOutput" value="false" />
   <parameter name="systemFrequency" value="80000000" />
  </module>
- <module kind="altera_avalon_uart" version="13.1" enabled="1" name="uart_0">
+ <module
+   kind="altera_avalon_uart"
+   version="13.0.1.99.2"
+   enabled="1"
+   name="uart_0">
   <parameter name="baud" value="115200" />
   <parameter name="dataBits" value="8" />
   <parameter name="fixedBaud" value="false" />
@@ -459,7 +461,11 @@
   <parameter name="useRelativePathForSimFile" value="false" />
   <parameter name="clockRate" value="80000000" />
  </module>
- <module kind="altera_avalon_spi" version="13.1" enabled="1" name="spi_1">
+ <module
+   kind="altera_avalon_spi"
+   version="13.0.1.99.2"
+   enabled="1"
+   name="spi_1">
   <parameter name="clockPhase" value="1" />
   <parameter name="clockPolarity" value="1" />
   <parameter name="dataWidth" value="8" />
@@ -475,7 +481,11 @@
   <parameter name="avalonSpec" value="2.0" />
   <parameter name="inputClockRate" value="80000000" />
  </module>
- <module kind="altera_avalon_pio" version="13.1" enabled="1" name="pio_0">
+ <module
+   kind="altera_avalon_pio"
+   version="13.0.1.99.2"
+   enabled="1"
+   name="pio_0">
   <parameter name="bitClearingEdgeCapReg" value="false" />
   <parameter name="bitModifyingOutReg" value="true" />
   <parameter name="captureEdge" value="false" />
@@ -491,9 +501,9 @@
  </module>
  <module
    kind="altera_avalon_pio"
-   version="13.1"
+   version="13.0.1.99.2"
    enabled="1"
-   name="correction_dc">
+   name="iq_corr_rx_phase_gain">
   <parameter name="bitClearingEdgeCapReg" value="false" />
   <parameter name="bitModifyingOutReg" value="false" />
   <parameter name="captureEdge" value="false" />
@@ -509,9 +519,9 @@
  </module>
  <module
    kind="altera_avalon_pio"
-   version="13.1"
+   version="13.0.1.99.2"
    enabled="1"
-   name="correction_phase_gain">
+   name="iq_corr_tx_phase_gain">
   <parameter name="bitClearingEdgeCapReg" value="false" />
   <parameter name="bitModifyingOutReg" value="false" />
   <parameter name="captureEdge" value="false" />
@@ -535,7 +545,7 @@
  </module>
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.instruction_master"
    end="nios2_qsys_0.jtag_debug_module">
   <parameter name="arbitrationPriority" value="1" />
@@ -544,24 +554,24 @@
  </connection>
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="nios2_qsys_0.jtag_debug_module">
   <parameter name="arbitrationPriority" value="1" />
   <parameter name="baseAddress" value="0x8800" />
   <parameter name="defaultConnection" value="false" />
  </connection>
- <connection kind="clock" version="13.1" start="clk_0.clk" end="nios2_qsys_0.clk" />
+ <connection kind="clock" version="13.0" start="clk_0.clk" end="nios2_qsys_0.clk" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
    end="nios2_qsys_0.reset_n" />
- <connection kind="clock" version="13.1" start="clk_0.clk" end="spi_0.clk" />
- <connection kind="reset" version="13.1" start="clk_0.clk_reset" end="spi_0.reset" />
+ <connection kind="clock" version="13.0" start="clk_0.clk" end="spi_0.clk" />
+ <connection kind="reset" version="13.0" start="clk_0.clk_reset" end="spi_0.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="spi_0.spi_control_port">
   <parameter name="arbitrationPriority" value="1" />
@@ -570,20 +580,20 @@
  </connection>
  <connection
    kind="interrupt"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.d_irq"
    end="spi_0.irq">
   <parameter name="irqNumber" value="0" />
  </connection>
- <connection kind="clock" version="13.1" start="clk_0.clk" end="jtag_uart_0.clk" />
+ <connection kind="clock" version="13.0" start="clk_0.clk" end="jtag_uart_0.clk" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
    end="jtag_uart_0.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="jtag_uart_0.avalon_jtag_slave">
   <parameter name="arbitrationPriority" value="1" />
@@ -592,39 +602,39 @@
  </connection>
  <connection
    kind="interrupt"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.d_irq"
    end="jtag_uart_0.irq">
   <parameter name="irqNumber" value="1" />
  </connection>
  <connection
    kind="clock"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk"
    end="onchip_memory2_0.clk1" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
    end="onchip_memory2_0.reset1" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="onchip_memory2_0.s1">
   <parameter name="arbitrationPriority" value="1" />
   <parameter name="baseAddress" value="0x4000" />
   <parameter name="defaultConnection" value="false" />
  </connection>
- <connection kind="clock" version="13.1" start="clk_0.clk" end="timer_0.clk" />
+ <connection kind="clock" version="13.0" start="clk_0.clk" end="timer_0.clk" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
    end="timer_0.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="timer_0.s1">
   <parameter name="arbitrationPriority" value="1" />
@@ -633,29 +643,29 @@
  </connection>
  <connection
    kind="interrupt"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.d_irq"
    end="timer_0.irq">
   <parameter name="irqNumber" value="2" />
  </connection>
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.instruction_master"
    end="onchip_memory2_0.s1">
   <parameter name="arbitrationPriority" value="1" />
   <parameter name="baseAddress" value="0x4000" />
   <parameter name="defaultConnection" value="false" />
  </connection>
- <connection kind="clock" version="13.1" start="clk_0.clk" end="uart_0.clk" />
+ <connection kind="clock" version="13.0" start="clk_0.clk" end="uart_0.clk" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
    end="uart_0.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="uart_0.s1">
   <parameter name="arbitrationPriority" value="1" />
@@ -664,16 +674,16 @@
  </connection>
  <connection
    kind="interrupt"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.d_irq"
    end="uart_0.irq">
   <parameter name="irqNumber" value="3" />
  </connection>
- <connection kind="clock" version="13.1" start="clk_0.clk" end="spi_1.clk" />
- <connection kind="reset" version="13.1" start="clk_0.clk_reset" end="spi_1.reset" />
+ <connection kind="clock" version="13.0" start="clk_0.clk" end="spi_1.clk" />
+ <connection kind="reset" version="13.0" start="clk_0.clk_reset" end="spi_1.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="spi_1.spi_control_port">
   <parameter name="arbitrationPriority" value="1" />
@@ -682,76 +692,80 @@
  </connection>
  <connection
    kind="interrupt"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.d_irq"
    end="spi_1.irq">
   <parameter name="irqNumber" value="4" />
  </connection>
- <connection kind="clock" version="13.1" start="clk_0.clk" end="pio_0.clk" />
- <connection kind="reset" version="13.1" start="clk_0.clk_reset" end="pio_0.reset" />
+ <connection kind="clock" version="13.0" start="clk_0.clk" end="pio_0.clk" />
+ <connection kind="reset" version="13.0" start="clk_0.clk_reset" end="pio_0.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="pio_0.s1">
   <parameter name="arbitrationPriority" value="1" />
   <parameter name="baseAddress" value="0x9040" />
   <parameter name="defaultConnection" value="false" />
  </connection>
- <connection kind="clock" version="13.1" start="clk_0.clk" end="correction_dc.clk" />
+ <connection
+   kind="clock"
+   version="13.0"
+   start="clk_0.clk"
+   end="iq_corr_rx_phase_gain.clk" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
-   end="correction_dc.reset" />
+   end="iq_corr_rx_phase_gain.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
-   end="correction_dc.s1">
+   end="iq_corr_rx_phase_gain.s1">
   <parameter name="arbitrationPriority" value="1" />
   <parameter name="baseAddress" value="0x0000" />
   <parameter name="defaultConnection" value="false" />
  </connection>
  <connection
    kind="clock"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk"
-   end="correction_phase_gain.clk" />
+   end="iq_corr_tx_phase_gain.clk" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
-   end="correction_phase_gain.reset" />
+   end="iq_corr_tx_phase_gain.reset" />
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
-   end="correction_phase_gain.s1">
+   end="iq_corr_tx_phase_gain.s1">
   <parameter name="arbitrationPriority" value="1" />
   <parameter name="baseAddress" value="0x9100" />
   <parameter name="defaultConnection" value="false" />
  </connection>
  <connection
    kind="clock"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk"
    end="bladerf_oc_i2c_master_0.clock_sink" />
  <connection
    kind="reset"
-   version="13.1"
+   version="13.0"
    start="clk_0.clk_reset"
    end="bladerf_oc_i2c_master_0.reset_sink" />
  <connection
    kind="interrupt"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.d_irq"
    end="bladerf_oc_i2c_master_0.interrupt_sender">
   <parameter name="irqNumber" value="5" />
  </connection>
  <connection
    kind="avalon"
-   version="13.1"
+   version="13.0"
    start="nios2_qsys_0.data_master"
    end="bladerf_oc_i2c_master_0.bladerf_oc_i2c_master">
   <parameter name="arbitrationPriority" value="1" />
diff --git a/hdl/fpga/ip/altera/nios_system/software/lms_spi_controller/lms_spi_controller.c b/hdl/fpga/ip/altera/nios_system/software/lms_spi_controller/lms_spi_controller.c
index 44882476ac66ca9990157aad0c9331e20b294096..29216f5d7ded6d67c9b6f42560a19029371c28bf 100644
--- a/hdl/fpga/ip/altera/nios_system/software/lms_spi_controller/lms_spi_controller.c
+++ b/hdl/fpga/ip/altera/nios_system/software/lms_spi_controller/lms_spi_controller.c
@@ -67,6 +67,13 @@
 #define OC_I2C_RXACK        (1<<7)
 #define OC_I2C_NACK         (1<<3)
 
+#define DEFAULT_GAIN_CORRECTION 0x1000
+#define GAIN_OFFSET 0
+#define DEFAULT_PHASE_CORRECTION 0x0000
+#define PHASE_OFFSET 16
+#define DEFAULT_CORRECTION ( (DEFAULT_PHASE_CORRECTION << PHASE_OFFSET)|  (DEFAULT_GAIN_CORRECTION << GAIN_OFFSET))
+
+
 void si5338_complete_transfer( uint8_t check_rxack ) {
     if( (IORD_8DIRECT(I2C, OC_I2C_CMD_STATUS)&OC_I2C_TIP) == 0 ) {
         while( (IORD_8DIRECT(I2C, OC_I2C_CMD_STATUS)&OC_I2C_TIP) == 0 ) { } ;
@@ -205,8 +212,8 @@ int main()
   IOWR_ALTERA_AVALON_UART_DIVISOR(UART_0_BASE, 19) ;
 
   // Set the IQ Correction parameters to 0
-  IOWR_ALTERA_AVALON_PIO_DATA(CORRECTION_DC_BASE, 0);
-  IOWR_ALTERA_AVALON_PIO_DATA(CORRECTION_PHASE_GAIN_BASE, 4096);
+  IOWR_ALTERA_AVALON_PIO_DATA(IQ_CORR_RX_PHASE_GAIN_BASE, DEFAULT_CORRECTION);
+  IOWR_ALTERA_AVALON_PIO_DATA(IQ_CORR_TX_PHASE_GAIN_BASE, DEFAULT_CORRECTION);
 
   /* Event loop never exits. */
   {
@@ -308,11 +315,11 @@ int main()
                         case 0:case 1:case 2: case 3:
                             device = PIO_0_BASE;break;
                         case 4: case 5: case 6: case 7:
-                            device = CORRECTION_DC_BASE;
+                            device = IQ_CORR_RX_PHASE_GAIN_BASE;
                             cmd_ptr->addr -= 4;
                             break;
                         case 8: case 9: case 10: case 11:
-                            device = CORRECTION_PHASE_GAIN_BASE;
+                            device = IQ_CORR_TX_PHASE_GAIN_BASE;
                             cmd_ptr->addr -= 8;
                             break;
                         case 12: case 13: case 14: case 15:
diff --git a/hdl/fpga/platforms/bladerf/vhdl/bladerf-hosted.vhd b/hdl/fpga/platforms/bladerf/vhdl/bladerf-hosted.vhd
index edded09bec00959d53591a3d6107c9fbce19f335..1d57e6d6d7f8201e54b38ad4c9e449a483ee5b5b 100644
--- a/hdl/fpga/platforms/bladerf/vhdl/bladerf-hosted.vhd
+++ b/hdl/fpga/platforms/bladerf/vhdl/bladerf-hosted.vhd
@@ -51,8 +51,8 @@ architecture hosted_bladerf of bladerf is
         oc_i2c_arst_i       : in  std_logic;
         oc_i2c_scl_pad_i    : in  std_logic;
         gpio_export         : out std_logic_vector(31 downto 0); 
-        correction_dc_export : out std_logic_vector(31 downto 0);
-        correction_phase_gain_export : out std_logic_vector(31 downto 0)
+        correction_rx_phase_gain_export : out std_logic_vector(31 downto 0);
+        correction_tx_phase_gain_export : out std_logic_vector(31 downto 0)
       );
     end component nios_system;
 
@@ -67,8 +67,8 @@ architecture hosted_bladerf of bladerf is
     signal nios_gpio        : std_logic_vector(31 downto 0) := x"0000_00d7" ;
 
 
-    signal correction_dc_export :  std_logic_vector(31 downto 0);
-    signal correction_phase_gain_export :  std_logic_vector(31 downto 0);
+    signal correction_rx_phase_gain :  std_logic_vector(31 downto 0);
+    signal correction_tx_phase_gain :  std_logic_vector(31 downto 0);
 
     signal i2c_scl_in       : std_logic ;
     signal i2c_scl_out      : std_logic ;
@@ -155,20 +155,26 @@ architecture hosted_bladerf of bladerf is
     signal rx_mux_q             :   signed(11 downto 0) ;
     signal rx_mux_valid         :   std_logic ;
 
+    signal rx_sample_corrected_i : signed(15 downto 0);
+    signal rx_sample_corrected_q : signed(15 downto 0);
+    signal rx_sample_corrected_valid : std_logic;
+
 
     signal correction_valid : std_logic;
 
-    signal correction_phase :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * PHASE_OFFSET)),DC_WIDTH);
-    signal correction_gain  :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * DC_OFFSET_REAL)),DC_WIDTH);
-    signal correction_dc_real :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * DC_OFFSET_IMAG)),DC_WIDTH);
-    signal correction_dc_imag :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * GAIN_OFFSET)),DC_WIDTH);
+    signal correction_tx_phase :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * PHASE_OFFSET)),DC_WIDTH);
+    signal correction_tx_gain  :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * DC_OFFSET_REAL)),DC_WIDTH);
+    signal correction_rx_phase :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * PHASE_OFFSET)),DC_WIDTH);
+    signal correction_rx_gain  :  signed(15 downto 0);--to_signed(integer(round(real(2**Q_SCALE) * DC_OFFSET_REAL)),DC_WIDTH);
+
+    constant FPGA_DC_CORRECTION :  signed(15 downto 0) := to_signed(integer(0), 16);
 
 begin
 
-    correction_phase <= signed(correction_phase_gain_export(31 downto 16));
-    correction_gain  <= signed(correction_phase_gain_export(15 downto 0));
-    correction_dc_real <= signed(correction_dc_export(31 downto 16));
-    correction_dc_imag <= signed(correction_dc_export(15 downto 0));
+    correction_tx_phase <= signed(correction_tx_phase_gain(31 downto 16));
+    correction_tx_gain  <= signed(correction_tx_phase_gain(15 downto 0));
+    correction_rx_phase <= signed(correction_rx_phase_gain(31 downto 16));
+    correction_rx_gain  <= signed(correction_rx_phase_gain(15 downto 0));
     correction_valid <= '1';
 
 
@@ -346,15 +352,38 @@ begin
         fifo_data           =>  rx_sample_fifo.wdata,
         fifo_write          =>  rx_sample_fifo.wreq,
 
-        in_i                =>  resize(rx_mux_i,16),
-        in_q                =>  resize(rx_mux_q,16),
-        in_valid            =>  rx_mux_valid,
+        in_i                =>  rx_sample_corrected_i,
+        in_q                =>  rx_sample_corrected_q,
+        in_valid            =>  rx_sample_corrected_valid,
 
         overflow_led        =>  rx_overflow_led,
         overflow_count      =>  rx_overflow_count,
         overflow_duration   =>  x"abcd"
       ) ;
 
+    U_rx_iq_correction : entity work.iq_correction(rx)
+        generic map(
+            INPUT_WIDTH => 16
+        )
+        port map(
+            reset => rx_reset,
+            clock => rx_clock,
+
+            in_real => resize(rx_mux_i,16),
+            in_imag => resize(rx_mux_q,16),
+            in_valid => rx_mux_valid,
+
+            out_real => rx_sample_corrected_i,
+            out_imag => rx_sample_corrected_q,
+            out_valid => rx_sample_corrected_valid,
+
+            dc_real => FPGA_DC_CORRECTION,
+            dc_imag => FPGA_DC_CORRECTION,
+            gain => correction_rx_gain,
+            phase => correction_rx_phase,
+            correction_valid => correction_valid
+      );
+
     U_fifo_reader : entity work.fifo_reader
       port map (
         clock               =>  tx_clock,
@@ -391,10 +420,10 @@ begin
             out_imag => tx_sample_q,
             out_valid => tx_sample_valid,
 
-            dc_real => correction_dc_real,
-            dc_imag => correction_dc_imag,
-            gain => correction_gain,
-            phase => correction_phase,
+            dc_real => FPGA_DC_CORRECTION,
+            dc_imag => FPGA_DC_CORRECTION,
+            gain => correction_tx_gain,
+            phase => correction_tx_phase,
             correction_valid => correction_valid
       );
 
@@ -499,8 +528,8 @@ begin
         uart_rxd            => fx3_uart_txd,
         uart_txd            => fx3_uart_rxd,
         gpio_export         => nios_gpio,
-        correction_dc_export            => correction_dc_export,
-        correction_phase_gain_export    => correction_phase_gain_export,
+        correction_tx_phase_gain_export    => correction_tx_phase_gain,
+        correction_rx_phase_gain_export    => correction_rx_phase_gain,
         oc_i2c_scl_pad_o    => i2c_scl_out,
         oc_i2c_scl_padoen_o => i2c_scl_oen,
         oc_i2c_sda_pad_i    => i2c_sda_in,
diff --git a/host/libraries/libbladeRF/include/libbladeRF.h b/host/libraries/libbladeRF/include/libbladeRF.h
index f655d1390a18d014f1914a06a44a227fcd899bdc..6b68eed206c273e80c9a6f519c0528d545f47092 100644
--- a/host/libraries/libbladeRF/include/libbladeRF.h
+++ b/host/libraries/libbladeRF/include/libbladeRF.h
@@ -248,6 +248,21 @@ typedef enum
 } bladerf_cal_module;
 
 /**
+ * IQ Correction Modules
+ */
+typedef enum
+{
+    BLADERF_IQ_CORR_TX_DC_I,
+    BLADERF_IQ_CORR_TX_DC_Q,
+    BLADERF_IQ_CORR_RX_DC_I,
+    BLADERF_IQ_CORR_RX_DC_Q,
+    BLADERF_IQ_CORR_RX_PHASE,
+    BLADERF_IQ_CORR_RX_GAIN,
+    BLADERF_IQ_CORR_TX_PHASE,
+    BLADERF_IQ_CORR_TX_GAIN
+} bladerf_correction_module;
+
+/**
  * Transmit Loopback options
  */
 typedef enum {
@@ -1529,7 +1544,8 @@ int CALL_CONV bladerf_config_gpio_write(struct bladerf *dev, uint32_t val);
  *
  * @return 0 on success, value from \ref RETCODES list on failure
  */
-API_EXPORT int bladerf_config_dc_gain_write(struct bladerf *dev, int16_t dc_i, int16_t dc_q);
+API_EXPORT 
+int bladerf_set_correction(struct bladerf *dev, bladerf_correction_module module, int16_t value);
 
 
 /**
@@ -1538,7 +1554,8 @@ API_EXPORT int bladerf_config_dc_gain_write(struct bladerf *dev, int16_t dc_i, i
  *
  * @return 0 on success, value from \ref RETCODES list on failure
  */
-API_EXPORT int bladerf_phase_gain_write(struct bladerf *dev, int16_t phase, uint16_t gain);
+API_EXPORT 
+int bladerf_print_correction(struct bladerf *dev, bladerf_correction_module module, int16_t *value);
 
 
 /**
diff --git a/host/libraries/libbladeRF/src/backend/libusb.c b/host/libraries/libbladeRF/src/backend/libusb.c
index 7fc73416aaf8c3786e6cca8c87117e595fdb8f17..3496c97510a0ce8a4c2d576ee903198b60c50795 100644
--- a/host/libraries/libbladeRF/src/backend/libusb.c
+++ b/host/libraries/libbladeRF/src/backend/libusb.c
@@ -1533,104 +1533,6 @@ static int lusb_config_gpio_read(struct bladerf *dev, uint32_t *val)
     return status;
 }
 
-static int lusb_set_phase_gain_correction(struct bladerf *dev, int16_t phase, uint16_t gain)
-{
-    int i = 0;
-    int status = 0;
-    uint32_t tmp_data;
-    struct uart_cmd cmd;
-    struct bladerf_lusb *lusb = dev->backend;
-
-    tmp_data = (((uint32_t) phase) << 16 )| (gain);
-
-    for (i = 0; status == 0 && i < 4; i++) {
-        cmd.addr = i + UART_PKT_DEV_GAIN_PHASE_CORR_ADDR;
-
-        cmd.data = (tmp_data>>(8*i))&0xff;
-        status = access_peripheral(
-                                    lusb,
-                                    UART_PKT_DEV_GPIO,
-                                    UART_PKT_MODE_DIR_WRITE,
-                                    &cmd
-                                  );
-
-        if (status < 0) {
-            break;
-        }
-    }
-
-    if (status < 0) {
-        bladerf_set_error(&dev->error, ETYPE_LIBBLADERF, status);
-    }
-
-    return status;
-}
-
-static int lusb_set_dc_correction(struct bladerf *dev, int16_t dc_real, int16_t dc_imag)
-{
-    int i = 0;
-    int status = 0;
-    uint32_t tmp_data;
-    struct uart_cmd cmd;
-    struct bladerf_lusb *lusb = dev->backend;
-
-    tmp_data = (((uint32_t)dc_imag) << 16 )| (dc_real & 0xffff);
-
-    for (i = 0; status == 0 && i < 4; i++) {
-        cmd.addr = i + UART_PKT_DEV_DC_CORR_ADDR;
-
-        cmd.data = (tmp_data>>(8*i))&0xff;
-        status = access_peripheral(
-                                    lusb,
-                                    UART_PKT_DEV_GPIO,
-                                    UART_PKT_MODE_DIR_WRITE,
-                                    &cmd
-                                  );
-
-        if (status < 0) {
-            break;
-        }
-    }
-
-    if (status < 0) {
-        bladerf_set_error(&dev->error, ETYPE_LIBBLADERF, status);
-    }
-
-    return status;
-}
-
-/*static int lusb_get_dc_correction(struct bladerf *dev, int16_t *dc_real, int16_t *dc_imag)
-{
-    int i = 0;
-    int status = 0;
-    struct uart_cmd cmd;
-    struct bladerf_lusb *lusb = dev->backend;
-    uint32_t tmp_data = 0;
-
-    for (i = 0; status == 0 && i < 4; i++){
-        cmd.addr = i + UART_PKT_DEV_DC_CORR_ADDR;
-        cmd.data = 0xff;
-
-        status = access_peripheral(
-                                    lusb,
-                                    UART_PKT_DEV_GPIO,
-                                    UART_PKT_MODE_DIR_READ,
-                                    &cmd
-                                    );
-
-        if (status < 0) {
-            break;
-        }
-        tmp_data |= (cmd.data << (i * 8));
-    }
-    if (status < 0){
-        bladerf_set_error(&dev->error, ETYPE_LIBBLADERF,status);
-    }
-
-    return status;
-}
-*/
-
 static int lusb_si5338_write(struct bladerf *dev, uint8_t addr, uint8_t data)
 {
     int status;
@@ -1747,6 +1649,148 @@ static int lusb_dac_write(struct bladerf *dev, uint16_t value)
     return status;
 }
 
+
+
+static int set_fpga_correction(struct bladerf *dev, uint16_t addr, int16_t value)
+{
+    int i = 0;
+    int status = 0;
+    struct uart_cmd cmd;
+    struct bladerf_lusb *lusb = dev->backend;
+
+    for (i = 0; status == 0 && i < 2; i++) {
+        cmd.addr = i + addr;
+
+        cmd.data = (value>>(8*i))&0xff;
+        status = access_peripheral(
+                                    lusb,
+                                    UART_PKT_DEV_GPIO,
+                                    UART_PKT_MODE_DIR_WRITE,
+                                    &cmd
+                                  );
+
+        if (status < 0) {
+            break;
+        }
+    }
+
+    if (status < 0) {
+        bladerf_set_error(&dev->error, ETYPE_LIBBLADERF, status);
+    }
+    return status;
+}
+
+static int lusb_set_correction(struct bladerf *dev, bladerf_correction_module module, int16_t value)
+{
+    int status = 0;
+    uint16_t addr = UART_PKT_DEV_RX_PHASE_ADDR;
+    struct bladerf_lusb *lusb = dev->backend;
+
+    switch(module)
+    {
+        case BLADERF_IQ_CORR_TX_GAIN:   addr += 2;
+        case BLADERF_IQ_CORR_TX_PHASE:  addr += 2;
+        case BLADERF_IQ_CORR_RX_GAIN:   addr += 2;
+        case BLADERF_IQ_CORR_RX_PHASE:
+            status = set_fpga_correction(dev,addr,value);
+            break;
+        case BLADERF_IQ_CORR_TX_DC_I:  
+            if(value < 0)
+                value =  abs(value) | (1 << 5);
+            status = lusb_lms_write(dev,0x42,(uint8_t)value);
+            break;  
+        case BLADERF_IQ_CORR_TX_DC_Q:
+            if(value < 0)
+                value =  abs(value) | (1 << 5);
+            status = lusb_lms_write(dev,0x43,(uint8_t)value);
+            break;  
+        case BLADERF_IQ_CORR_RX_DC_I:
+            if(value < 0)
+                value =  abs(value) | (1 << 5);
+            status = lusb_lms_write(dev,0x71,(uint8_t)value);
+            break;  
+        case BLADERF_IQ_CORR_RX_DC_Q:
+            if(value < 0)
+                value = abs(value) | (1 << 5);
+            status = lusb_lms_write(dev,0x72,(uint8_t)value);
+            break;  
+        default:    
+            break;
+    }
+
+    return status;
+}
+
+
+static int print_fpga_correction(struct bladerf *dev, uint16_t addr, int16_t *value)
+{
+    int i = 0;
+    int status = 0;
+    struct uart_cmd cmd;
+    struct bladerf_lusb *lusb = dev->backend;
+
+	*value = 0;
+    for (i = 0; status == 0 && i < 2; i++) {
+        cmd.addr = i + addr;
+		cmd.data = 0xff;
+        status = access_peripheral(
+                                    lusb,
+                                    UART_PKT_DEV_GPIO,
+                                    UART_PKT_MODE_DIR_READ,
+                                    &cmd
+                                  );
+
+		*value |= (cmd.data << (i*8));
+
+        if (status < 0) {
+            break;
+        }
+    }
+
+    if (status < 0) {
+        bladerf_set_error(&dev->error, ETYPE_LIBBLADERF, status);
+    }
+    return status;
+}
+
+static int lusb_print_correction(struct bladerf *dev, bladerf_correction_module module, int16_t *value)
+{    
+    int status = 0;
+	uint8_t tmp;
+    uint16_t addr = UART_PKT_DEV_RX_PHASE_ADDR;
+    struct bladerf_lusb *lusb = dev->backend;
+
+    switch(module)
+    {
+        case BLADERF_IQ_CORR_TX_GAIN:   addr += 2;
+        case BLADERF_IQ_CORR_TX_PHASE:  addr += 2;
+        case BLADERF_IQ_CORR_RX_GAIN:   addr += 2;
+        case BLADERF_IQ_CORR_RX_PHASE:
+            status = print_fpga_correction(dev,addr,value);
+            break;
+        case BLADERF_IQ_CORR_TX_DC_I:  
+            status = lusb_lms_read(dev,0x42,&tmp);
+			*value = tmp;
+            break;  
+        case BLADERF_IQ_CORR_TX_DC_Q:
+            status = lusb_lms_read(dev,0x43,&tmp);
+			*value = tmp;
+            break;  
+        case BLADERF_IQ_CORR_RX_DC_I:
+            status = lusb_lms_read(dev,0x71,&tmp);
+			*value = tmp;
+            break;  
+        case BLADERF_IQ_CORR_RX_DC_Q:
+            status = lusb_lms_read(dev,0x72,&tmp);
+			*value = tmp;
+            break;  
+        default:    
+            break;
+    }
+
+    return status;
+}
+
 static int lusb_tx(struct bladerf *dev, bladerf_format format, void *samples,
                    int n, struct bladerf_metadata *metadata)
 {
@@ -2222,8 +2266,8 @@ const struct bladerf_fn bladerf_lusb_fn = {
     FIELD_INIT(.config_gpio_write, lusb_config_gpio_write),
     FIELD_INIT(.config_gpio_read, lusb_config_gpio_read),
 
-    FIELD_INIT(.config_dc_gain_write, lusb_set_dc_correction),
-    FIELD_INIT(.phase_gain_write, lusb_set_phase_gain_correction),
+    FIELD_INIT(.set_correction, lusb_set_correction),
+    FIELD_INIT(.print_correction, lusb_print_correction),
 
     FIELD_INIT(.si5338_write, lusb_si5338_write),
     FIELD_INIT(.si5338_read, lusb_si5338_read),
diff --git a/host/libraries/libbladeRF/src/bladerf.c b/host/libraries/libbladeRF/src/bladerf.c
index 8e8837c85b0d9eb4f29637f2f63b41d53200fcb0..96e56e5e08e7741677e1ff6e5d65d7d34ae6f09f 100644
--- a/host/libraries/libbladeRF/src/bladerf.c
+++ b/host/libraries/libbladeRF/src/bladerf.c
@@ -1067,14 +1067,14 @@ int bladerf_config_gpio_write(struct bladerf *dev, uint32_t val)
 /*------------------------------------------------------------------------------
  * IQ Calibration routines
  *----------------------------------------------------------------------------*/
-int bladerf_config_dc_gain_write(struct bladerf *dev, int16_t dc_i, int16_t dc_q)
+int bladerf_set_correction(struct bladerf *dev, bladerf_correction_module module, int16_t value)
 {
-    return dev->fn->config_dc_gain_write(dev,dc_i,dc_q);   
+    return dev->fn->set_correction(dev,module,value);   
 }
 
-int bladerf_phase_gain_write(struct bladerf *dev, int16_t phase, uint16_t gain)
+int bladerf_print_correction(struct bladerf *dev, bladerf_correction_module module, int16_t *value)
 {
-    return dev->fn->phase_gain_write(dev,phase,gain);
+    return dev->fn->print_correction(dev,module,value);
 }
 
 
diff --git a/host/libraries/libbladeRF/src/bladerf_priv.h b/host/libraries/libbladeRF/src/bladerf_priv.h
index b00a2df009038a0e10cd05df4108ce4fde1c83e1..d4b589fb75f5ddc90b6b592ecc7f859697c3ddea 100644
--- a/host/libraries/libbladeRF/src/bladerf_priv.h
+++ b/host/libraries/libbladeRF/src/bladerf_priv.h
@@ -124,8 +124,8 @@ struct bladerf_fn {
     int (*config_gpio_read)(struct bladerf *dev, uint32_t *val);
 
     /* IQ Calibration Settings */
-    int (*config_dc_gain_write)(struct bladerf *deev, int16_t dc_i, int16_t dc_q);
-    int (*phase_gain_write)(struct bladerf *deev, int16_t phase, uint16_t gain);
+    int (*set_correction)(struct bladerf *dev, bladerf_correction_module module, int16_t value);
+    int (*print_correction)(struct bladerf *dev, bladerf_correction_module module, int16_t *value);
 
     /* Si5338 accessors */
     int (*si5338_write)(struct bladerf *dev, uint8_t addr, uint8_t data);
diff --git a/host/utilities/bladeRF-cli/CMakeLists.txt b/host/utilities/bladeRF-cli/CMakeLists.txt
index 06431848c94110ad8be87bef243349b6044343bc..9978ff0ed7ca36029a6a622e7973bc6f267d9352 100644
--- a/host/utilities/bladeRF-cli/CMakeLists.txt
+++ b/host/utilities/bladeRF-cli/CMakeLists.txt
@@ -122,8 +122,7 @@ set(BLADERF_CLI_SOURCE
         src/cmd/recover.c
         src/cmd/jump_boot.c
         src/cmd/mimo.c
-        src/cmd/dc_gain.c
-        src/cmd/phase_gain.c
+        src/cmd/correct.c
         src/interactive/interactive.c
         ${BLADERF_HOST_COMMON_SOURCE_DIR}/conversions.c
         ${BLADERF_HOST_COMMON_SOURCE_DIR}/log.c
diff --git a/host/utilities/bladeRF-cli/src/cmd/cmd.c b/host/utilities/bladeRF-cli/src/cmd/cmd.c
index 498fb8920b7cce356c845b23f6ce411a8e088915..a9606315c7e54ac4fc6b4c1edd0697ff962eba3d 100644
--- a/host/utilities/bladeRF-cli/src/cmd/cmd.c
+++ b/host/utilities/bladeRF-cli/src/cmd/cmd.c
@@ -28,7 +28,7 @@
 #define DECLARE_CMD(x) int cmd_##x (struct cli_state *, int, char **)
 DECLARE_CMD(calibrate);
 DECLARE_CMD(clear);
-DECLARE_CMD(dc_gain);
+DECLARE_CMD(correct);
 DECLARE_CMD(echo);
 DECLARE_CMD(erase);
 DECLARE_CMD(flash_backup);
@@ -42,7 +42,6 @@ DECLARE_CMD(load);
 DECLARE_CMD(mimo);
 DECLARE_CMD(open);
 DECLARE_CMD(peek);
-DECLARE_CMD(phase_gain);
 DECLARE_CMD(poke);
 DECLARE_CMD(print);
 DECLARE_CMD(probe);
@@ -62,8 +61,7 @@ struct cmd {
     const char  *help;
 };
 
-static const char *cmd_names_dc_gain[] = { "dc_gain", "dc", NULL };
-static const char *cmd_names_phase_gain[] = {"phase_gain", NULL};
+static const char *cmd_names_correct[] = { "correct", NULL };
 static const char *cmd_names_calibrate[] = { "calibrate", "cal", NULL };
 static const char *cmd_names_clear[] = { "clear", "cls", NULL };
 static const char *cmd_names_echo[] = { "echo", NULL };
@@ -576,21 +574,11 @@ static const struct cmd cmd_table[] = {
         )
     },
     {
-        FIELD_INIT(.names, cmd_names_dc_gain),
-        FIELD_INIT(.exec, cmd_dc_gain),
-        FIELD_INIT(.desc, "Modify DC gain offset"),
+        FIELD_INIT(.names, cmd_names_correct),
+        FIELD_INIT(.exec, cmd_correct),
+        FIELD_INIT(.desc, "Correct for IQ Imbalances"),
         FIELD_INIT(.help,
-            "dc_gain <i_offset> <q_offset>\n"
-            "\n"
-            "Change the DC correction parameters for the IQ correction block.\n"
-        )
-    },
-    {
-        FIELD_INIT(.names, cmd_names_phase_gain),
-        FIELD_INIT(.exec, cmd_phase_gain),
-        FIELD_INIT(.desc, "Modify phase offset & gain"),
-        FIELD_INIT(.help,
-            "phase_gain [phase] [gain]\n"
+            "correct [tx|rx] [dc|phase|gain] [args]\n"
         )
     },
     /* Always terminate the command entry with a completely NULL entry */
diff --git a/host/utilities/bladeRF-cli/src/cmd/correct.c b/host/utilities/bladeRF-cli/src/cmd/correct.c
new file mode 100644
index 0000000000000000000000000000000000000000..fbcbe00c8b26169596c4ac043152193eb0b95788
--- /dev/null
+++ b/host/utilities/bladeRF-cli/src/cmd/correct.c
@@ -0,0 +1,131 @@
+/*
+ * This file is part of the bladeRF project
+ *
+ * Copyright (C) 2013 Nuand LLC
+ *
+ * This program is free software; you can redistribute it and/or modify
+ * it under the terms of the GNU General Public License as published by
+ * the Free Software Foundation; either version 2 of the License, or
+ * (at your option) any later version.
+ *
+ * This program is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License along
+ * with this program; if not, write to the Free Software Foundation, Inc.,
+ * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+ */
+#include <stdio.h>
+#include <string.h>
+#include <libbladeRF.h>
+
+#include "cmd.h"
+#include "conversions.h"
+
+#define MAX_DC_OFFSET 15
+#define MAX_PHASE (2048)
+#define MAX_GAIN (2048)
+
+int cmd_correct(struct cli_state *state, int argc, char **argv)
+{
+    int rv = CMD_RET_OK;
+    int status;
+    bool ok = true;
+    bool isTx = false;
+
+    if (!cli_device_is_opened(state))
+    {
+        return CMD_RET_NODEV;
+    }
+
+
+        //get the direction to print
+    if (argc >= 2)
+    {
+        if (!strcasecmp(argv[1],"tx"))
+            isTx = true;
+        else if(!strcasecmp(argv[1],"rx"))
+            isTx = false;
+        else
+            return CMD_RET_INVPARAM;
+    }
+
+    if( argc == 2 ) 
+    {
+        int16_t dc_i, dc_q, phase,gain;
+        //argv[1]
+        if(isTx)
+        {
+            status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_TX_DC_I, &dc_i);
+            status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_TX_DC_Q, &dc_q);
+            status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_TX_PHASE, &phase);
+            status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_TX_GAIN, &gain);
+        }
+        else
+        {
+			status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_RX_DC_I, &dc_i);
+            status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_RX_DC_Q, &dc_q);
+            status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_RX_PHASE, &phase);
+            status = bladerf_print_correction(state->dev,BLADERF_IQ_CORR_RX_GAIN, &gain);
+        }
+        printf("Current Settings: DC OFFSET I=%d Q=%d, Phase=%d, Gain=%d\n",dc_i,dc_q,phase,gain);
+    }
+    /* Parse the value */
+    else if( argc == 4 ) 
+    {
+		int16_t value = 0;
+
+        if (!strcasecmp(argv[2],"phase"))
+        {
+            value = str2int( argv[3], -MAX_PHASE ,MAX_PHASE, &ok );
+			if(isTx)
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_TX_PHASE, value);
+			else
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_RX_PHASE, value);
+					
+        }
+        else if (!strcasecmp(argv[2],"gain"))
+        {
+            value = str2int( argv[3], -MAX_GAIN ,MAX_GAIN, &ok );
+			if(isTx)
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_TX_GAIN, value);
+			else
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_RX_GAIN, value);
+        }
+        else
+        {
+            rv = CMD_RET_INVPARAM;
+        }
+    }
+    else if (argc == 5) //dc correction requires 2 parameters
+    {
+
+        if (!strcasecmp(argv[2],"dc"))
+        {
+			int16_t val_i,val_q;
+			
+            val_i = str2int( argv[3], -MAX_DC_OFFSET ,MAX_DC_OFFSET, &ok );
+            val_q = str2int( argv[4], -MAX_DC_OFFSET ,MAX_DC_OFFSET, &ok );
+			if(isTx)
+			{
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_TX_DC_I, val_i);
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_TX_DC_Q, val_q);
+			}
+			else
+			{
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_RX_DC_I, val_i);
+				status = bladerf_set_correction(state->dev,BLADERF_IQ_CORR_RX_DC_Q, val_q);
+			}
+
+        }
+
+    }     
+    else {
+        cli_err(state, argv[0], "Invalid number of arguments (%d)\n", argc);
+        rv = CMD_RET_INVPARAM;
+    }
+    return rv;
+}
+
diff --git a/host/utilities/bladeRF-cli/src/cmd/dc_gain.c b/host/utilities/bladeRF-cli/src/cmd/dc_gain.c
deleted file mode 100644
index a97d7900e8da7fbae7246a43d052a454b640681e..0000000000000000000000000000000000000000
--- a/host/utilities/bladeRF-cli/src/cmd/dc_gain.c
+++ /dev/null
@@ -1,85 +0,0 @@
-/*
- * This file is part of the bladeRF project
- *
- * Copyright (C) 2013 Nuand LLC
- *
- * This program is free software; you can redistribute it and/or modify
- * it under the terms of the GNU General Public License as published by
- * the Free Software Foundation; either version 2 of the License, or
- * (at your option) any later version.
- *
- * This program is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- * GNU General Public License for more details.
- *
- * You should have received a copy of the GNU General Public License along
- * with this program; if not, write to the Free Software Foundation, Inc.,
- * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
- */
-#include <stdio.h>
-#include <string.h>
-#include <libbladeRF.h>
-
-#include "cmd.h"
-#include "conversions.h"
-
-#define MAX_GAIN_SETTING ((1<<16) -1)
-
-int cmd_dc_gain(struct cli_state *state, int argc, char **argv)
-{
-    int rv = CMD_RET_OK;
-    int status;
-    bool ok = true;
-    int (*f)(struct bladerf *, int16_t, int16_t);
-    int dc_gain_i = 0,dc_gain_q = 0;
-
-    if (!cli_device_is_opened(state)) {
-        return CMD_RET_NODEV;
-    }
-
-    if( argc == 3 ) {
-
-        /* Parse the value */
-        if( argc == 3 ) {
-            dc_gain_i = str2int( argv[1], -MAX_GAIN_SETTING ,MAX_GAIN_SETTING, &ok );
-            if( !ok ) {
-                cli_err(state, argv[0],
-                        "Invalid I gain setting provided (%s)", argv[1]);
-                return CMD_RET_INVPARAM;
-            }
-            dc_gain_q = str2int( argv[2], (-MAX_GAIN_SETTING) ,MAX_GAIN_SETTING, &ok );
-            if( !ok ) {
-                cli_err(state, argv[0],
-                        "Invalid Q gain setting provided (%s)", argv[2]);
-                return CMD_RET_INVPARAM;
-            }
-            else
-            {
-                f = bladerf_config_dc_gain_write;
-            }
-        }
-
-        /* Write the value to the address */
-        if( rv == CMD_RET_OK && f ) {
-            status = f( state->dev, dc_gain_i, dc_gain_q );
-            if (status < 0) {
-                state->last_lib_error = status;
-                rv = CMD_RET_LIBBLADERF;
-            } else {
-                //printf( "  0x%2.2x: 0x%2.2x\n", address, value );
-            }
-        }
-
-    } 
-    else if(argc == 1) {
-        /* If the command is issued with no additional arguements read the current value*/
-
-    }
-    else {
-        cli_err(state, argv[0], "Invalid number of arguments (%d)\n", argc);
-        rv = CMD_RET_INVPARAM;
-    }
-    return rv;
-}
-
diff --git a/host/utilities/bladeRF-cli/src/cmd/phase_gain.c b/host/utilities/bladeRF-cli/src/cmd/phase_gain.c
deleted file mode 100644
index 89d97ce4a686e5fc007e16c24e98378bcf961c85..0000000000000000000000000000000000000000
--- a/host/utilities/bladeRF-cli/src/cmd/phase_gain.c
+++ /dev/null
@@ -1,79 +0,0 @@
-/*
- * This file is part of the bladeRF project
- *
- * Copyright (C) 2013 Nuand LLC
- *
- * This program is free software; you can redistribute it and/or modify
- * it under the terms of the GNU General Public License as published by
- * the Free Software Foundation; either version 2 of the License, or
- * (at your option) any later version.
- *
- * This program is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- * GNU General Public License for more details.
- *
- * You should have received a copy of the GNU General Public License along
- * with this program; if not, write to the Free Software Foundation, Inc.,
- * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
- */
-#include <stdio.h>
-#include <string.h>
-#include <libbladeRF.h>
-
-#include "cmd.h"
-#include "conversions.h"
-
-#define MAX_GAIN_SETTING ((1<<16) -1)
-
-int cmd_phase_gain(struct cli_state *state, int argc, char **argv)
-{
-    int rv = CMD_RET_OK;
-    int status;
-    bool ok = true;
-    int (*f)(struct bladerf *, int16_t, uint16_t);
-    int phase = 0,gain = 0;
-
-    if (!cli_device_is_opened(state)) {
-        return CMD_RET_NODEV;
-    }
-
-    if( argc == 3 ) {
-
-        /* Parse the value */
-        if( argc == 3 ) {
-            phase = str2int( argv[1], -MAX_GAIN_SETTING ,MAX_GAIN_SETTING, &ok );
-            if( !ok ) {
-                cli_err(state, argv[0],
-                        "Invalid phase offset setting provided (%s)", argv[1]);
-                return CMD_RET_INVPARAM;
-            }
-            gain = str2uint( argv[2], 0,MAX_GAIN_SETTING, &ok );
-            if( !ok ) {
-                cli_err(state, argv[0],
-                        "Invalid gain setting provided (%s)", argv[2]);
-                return CMD_RET_INVPARAM;
-            }
-            else
-            {
-                f = bladerf_phase_gain_write;
-            }
-        }
-
-        /* Write the value to the address */
-        if( rv == CMD_RET_OK && f ) {
-            status = f( state->dev, phase, gain );
-            if (status < 0) {
-                state->last_lib_error = status;
-                rv = CMD_RET_LIBBLADERF;
-            } else {
-                //printf( "  0x%2.2x: 0x%2.2x\n", address, value );
-            }
-        }
-
-    } else {
-        cli_err(state, argv[0], "Invalid number of arguments (%d)\n", argc);
-        rv = CMD_RET_INVPARAM;
-    }
-    return rv;
-}
