#!/bin/bash
#
# This script creates the ucosii_net_zipfs Board Support Package (BSP).

BSP_TYPE=hal
BSP_DIR=.
SOPC_DIR=../../
SOPC_FILE=Z:/work/nuandrelease/release/hdl/fpga/ip/altera/nios_system/nios_system.sopcinfo
NIOS2_BSP_ARGS="--set hal.max_file_descriptors 4 --set hal.enable_small_c_library true --set hal.sys_clk_timer none --set hal.timestamp_timer none --set hal.enable_exit false --set hal.enable_c_plus_plus false --set hal.enable_lightweight_device_driver_api true --set hal.enable_clean_exit false --set hal.enable_sim_optimize false --set hal.enable_reduced_device_drivers true  --set hal.make.bsp_cflags_optimization '-Os'"
CPU_NAME=


# Don't run make if create-this-app script is called with --no-make arg
SKIP_MAKE=
while [ $# -gt 0 ]
do
  case "$1" in
		--no-make)
        	SKIP_MAKE=1
        	;;
		*)
			NIOS2_BSP_ARGS="$NIOS2_BSP_ARGS $1"
			;;
  esac
  shift
done


# Run nios2-bsp utility to create a hal BSP in this directory
# for the system with a .sopc file in $SOPC_FILE.
# Deprecating $SOPC_DIR in 10.1. Multiple .sopcinfo files in a directory may exist.

if [ -z "$SOPC_FILE" ]; then
	echo "WARNING: Use of a directory for locating a .sopcinfo file is deprecated in 10.1. Multiple .sopcinfo files may exist. You must specify the full .sopcinfo path."
	cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_DIR $NIOS2_BSP_ARGS $CPU_NAME"
else
	cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_FILE $NIOS2_BSP_ARGS $CPU_NAME"
fi


echo "create-this-bsp: Running \"$cmd\""
$cmd || {
    echo "$cmd failed"
    exit 1
}
if [ -z "$SKIP_MAKE" ]; then
	echo "create-this-bsp: Running make"
	make
fi
