if(DEFINED __INCLUDED_BLADERF_FINDCYAPI_CMAKE)
    return()
endif()
set(__INCLUDED_BLADERF_FINDCYAPI_CMAKE TRUE)

if(NOT CYAPI_FOUND)

if(CYAPI_INCLUDE_DIR AND CYAPI_LIBRARIES)
  set(CYAPI_FOUND TRUE CACHE INTERNAL "CyAPI found")
  message(STATUS "Found CyAPI: ${CYAPI_INCLUDE_DIR}, ${CYAPI_LIBRARIES}")
else(CYAPI_INCLUDE_DIR AND CYAPI_LIBRARIES)
  set(CYAPI_FOUND FALSE CACHE INTERNAL "CyAPI found")
  message(STATUS "CyAPI not found.")
endif(CYAPI_INCLUDE_DIR AND CYAPI_LIBRARIES)

mark_as_advanced(CYAPI_INCLUDE_DIR CYAPI_LIBRARIES)

endif(NOT CYAPI_FOUND) 
